"""clean_init

Revision ID: 972606e48116
Revises: 
Create Date: 2026-10-05 00:13:23.443108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '972606e48116'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('economy_resources',
    sa.Column('external_resource_id', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('source_type', sa.Enum('RESOURCE_LOCATION', 'CITY_LOCATION', 'OTHER', name='resourcesourcetype'), nullable=False),
    sa.Column('is_tradeable', sa.Boolean(), nullable=False),
    sa.Column('base_sell_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('base_buy_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('min_sell_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_sell_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('min_buy_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('max_buy_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('category', sa.Enum('SWAMP', 'MINE', 'GEMS', 'LAKE', 'FOREST', 'SANDS', 'SKINS', name='resourcecategory'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('economy_resources_pkey')),
    sa.UniqueConstraint('external_resource_id', name=op.f('economy_resources_external_resource_id_key'))
    )
    op.create_index(op.f('economy_resources_category_idx'), 'economy_resources', ['category'], unique=False)
    op.create_index(op.f('economy_resources_code_idx'), 'economy_resources', ['code'], unique=True)
    op.create_index(op.f('economy_resources_order_idx'), 'economy_resources', ['order'], unique=False)
    op.create_index(op.f('economy_resources_source_type_idx'), 'economy_resources', ['source_type'], unique=False)
    op.create_table('economy_scheduler_state',
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('economy_scheduler_state_pkey'))
    )
    op.create_index(op.f('economy_scheduler_state_job_name_idx'), 'economy_scheduler_state', ['job_name'], unique=True)
    op.create_index(op.f('economy_scheduler_state_locked_until_idx'), 'economy_scheduler_state', ['locked_until'], unique=False)
    op.create_index(op.f('economy_scheduler_state_next_run_at_idx'), 'economy_scheduler_state', ['next_run_at'], unique=False)
    op.create_table('exchange_lots',
    sa.Column('owner_character_id', sa.UUID(), nullable=False),
    sa.Column('lot_type', sa.Enum('BUY', 'SELL', name='lottype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', name='lotstatus'), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('exchange_lots_pkey'))
    )
    op.create_index(op.f('exchange_lots_lot_type_idx'), 'exchange_lots', ['lot_type'], unique=False)
    op.create_index(op.f('exchange_lots_owner_character_id_idx'), 'exchange_lots', ['owner_character_id'], unique=False)
    op.create_index(op.f('exchange_lots_status_idx'), 'exchange_lots', ['status'], unique=False)
    op.create_table('price_recalculations',
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('STARTED', 'COMPLETED', 'FAILED', name='pricerecalculationstatus'), nullable=False),
    sa.Column('reason', sa.Enum('SCHEDULED', 'MANUAL', 'ADMIN_RESET', name='pricerecalculationreason'), nullable=False),
    sa.Column('next_recalculation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('price_recalculations_pkey'))
    )
    op.create_index(op.f('price_recalculations_next_recalculation_at_idx'), 'price_recalculations', ['next_recalculation_at'], unique=False)
    op.create_index(op.f('price_recalculations_reason_idx'), 'price_recalculations', ['reason'], unique=False)
    op.create_index(op.f('price_recalculations_started_at_idx'), 'price_recalculations', ['started_at'], unique=False)
    op.create_index(op.f('price_recalculations_status_idx'), 'price_recalculations', ['status'], unique=False)
    op.create_table('tavern_meals',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('health_restore', sa.Float(), nullable=False),
    sa.Column('tiredness_restore_percent', sa.Float(), nullable=False),
    sa.Column('ducats_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Integer(), server_default='500', nullable=False),
    sa.Column('default_stock', sa.Integer(), server_default='500', nullable=False),
    sa.Column('stock_period', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tavern_meals_pkey'))
    )
    op.create_index(op.f('tavern_meals_slug_idx'), 'tavern_meals', ['slug'], unique=True)
    op.create_table('buyout_stocks',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['economy_resources.id'], name=op.f('buyout_stocks_resource_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('buyout_stocks_pkey')),
    sa.UniqueConstraint('resource_id', name=op.f('buyout_stocks_resource_id_key'))
    )
    op.create_table('economy_transactions',
    sa.Column('transaction_type', sa.Enum('BUYOUT_BUY', 'BUYOUT_SELL', 'EXCHANGE_BUY', 'EXCHANGE_SELL', 'EXCHANGE_CANCEL', 'ADMIN_RESET', 'TAVERN_BUY', name='transactiontype'), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=True),
    sa.Column('seller_id', sa.UUID(), nullable=True),
    sa.Column('lot_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['exchange_lots.id'], name=op.f('economy_transactions_lot_id_fkey')),
    sa.ForeignKeyConstraint(['resource_id'], ['economy_resources.id'], name=op.f('economy_transactions_resource_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('economy_transactions_pkey'))
    )
    op.create_index(op.f('economy_transactions_buyer_id_idx'), 'economy_transactions', ['buyer_id'], unique=False)
    op.create_index(op.f('economy_transactions_lot_id_idx'), 'economy_transactions', ['lot_id'], unique=False)
    op.create_index(op.f('economy_transactions_resource_id_idx'), 'economy_transactions', ['resource_id'], unique=False)
    op.create_index(op.f('economy_transactions_seller_id_idx'), 'economy_transactions', ['seller_id'], unique=False)
    op.create_index(op.f('economy_transactions_transaction_type_idx'), 'economy_transactions', ['transaction_type'], unique=False)
    op.create_table('exchange_lot_items',
    sa.Column('lot_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['exchange_lots.id'], name=op.f('exchange_lot_items_lot_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['economy_resources.id'], name=op.f('exchange_lot_items_resource_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exchange_lot_items_pkey')),
    sa.UniqueConstraint('lot_id', 'resource_id', name='uq_exchange_lot_item')
    )
    op.create_index(op.f('exchange_lot_items_lot_id_idx'), 'exchange_lot_items', ['lot_id'], unique=False)
    op.create_index(op.f('exchange_lot_items_resource_id_idx'), 'exchange_lot_items', ['resource_id'], unique=False)
    op.create_table('price_recalculation_items',
    sa.Column('recalculation_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('old_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('new_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('buyout_previous_quantity', sa.Integer(), nullable=False),
    sa.Column('buyout_current_quantity', sa.Integer(), nullable=False),
    sa.Column('locations_previous_quantity', sa.Integer(), nullable=False),
    sa.Column('locations_current_quantity', sa.Integer(), nullable=False),
    sa.Column('players_previous_quantity', sa.Integer(), nullable=False),
    sa.Column('players_current_quantity', sa.Integer(), nullable=False),
    sa.Column('buyout_delta_percent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('locations_delta_percent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('players_delta_percent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('price_delta_percent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recalculation_id'], ['price_recalculations.id'], name=op.f('price_recalculation_items_recalculation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['economy_resources.id'], name=op.f('price_recalculation_items_resource_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('price_recalculation_items_pkey')),
    sa.UniqueConstraint('recalculation_id', 'resource_id', name='uq_price_recalculation_resource')
    )
    op.create_index(op.f('price_recalculation_items_recalculation_id_idx'), 'price_recalculation_items', ['recalculation_id'], unique=False)
    op.create_index(op.f('price_recalculation_items_resource_id_idx'), 'price_recalculation_items', ['resource_id'], unique=False)
    op.create_table('resource_current_prices',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('sell_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('previous_sell_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('previous_buy_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('last_recalculated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_recalculation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['economy_resources.id'], name=op.f('resource_current_prices_resource_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_current_prices_pkey')),
    sa.UniqueConstraint('resource_id', name=op.f('resource_current_prices_resource_id_key'))
    )
    op.create_table('resource_pool_snapshots',
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('recalculation_id', sa.UUID(), nullable=True),
    sa.Column('pool_type', sa.Enum('BUYOUT', 'LOCATIONS', 'PLAYERS', name='pooltype'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['recalculation_id'], ['price_recalculations.id'], name=op.f('resource_pool_snapshots_recalculation_id_fkey')),
    sa.ForeignKeyConstraint(['resource_id'], ['economy_resources.id'], name=op.f('resource_pool_snapshots_resource_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('resource_pool_snapshots_pkey'))
    )
    op.create_index(op.f('resource_pool_snapshots_recalculation_id_idx'), 'resource_pool_snapshots', ['recalculation_id'], unique=False)
    op.create_index(op.f('resource_pool_snapshots_resource_id_idx'), 'resource_pool_snapshots', ['resource_id'], unique=False)
    op.create_index(op.f('resource_pool_snapshots_snapshot_at_idx'), 'resource_pool_snapshots', ['snapshot_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('resource_pool_snapshots_snapshot_at_idx'), table_name='resource_pool_snapshots')
    op.drop_index(op.f('resource_pool_snapshots_resource_id_idx'), table_name='resource_pool_snapshots')
    op.drop_index(op.f('resource_pool_snapshots_recalculation_id_idx'), table_name='resource_pool_snapshots')
    op.drop_table('resource_pool_snapshots')
    op.drop_table('resource_current_prices')
    op.drop_index(op.f('price_recalculation_items_resource_id_idx'), table_name='price_recalculation_items')
    op.drop_index(op.f('price_recalculation_items_recalculation_id_idx'), table_name='price_recalculation_items')
    op.drop_table('price_recalculation_items')
    op.drop_index(op.f('exchange_lot_items_resource_id_idx'), table_name='exchange_lot_items')
    op.drop_index(op.f('exchange_lot_items_lot_id_idx'), table_name='exchange_lot_items')
    op.drop_table('exchange_lot_items')
    op.drop_index(op.f('economy_transactions_transaction_type_idx'), table_name='economy_transactions')
    op.drop_index(op.f('economy_transactions_seller_id_idx'), table_name='economy_transactions')
    op.drop_index(op.f('economy_transactions_resource_id_idx'), table_name='economy_transactions')
    op.drop_index(op.f('economy_transactions_lot_id_idx'), table_name='economy_transactions')
    op.drop_index(op.f('economy_transactions_buyer_id_idx'), table_name='economy_transactions')
    op.drop_table('economy_transactions')
    op.drop_table('buyout_stocks')
    op.drop_index(op.f('tavern_meals_slug_idx'), table_name='tavern_meals')
    op.drop_table('tavern_meals')
    op.drop_index(op.f('price_recalculations_status_idx'), table_name='price_recalculations')
    op.drop_index(op.f('price_recalculations_started_at_idx'), table_name='price_recalculations')
    op.drop_index(op.f('price_recalculations_reason_idx'), table_name='price_recalculations')
    op.drop_index(op.f('price_recalculations_next_recalculation_at_idx'), table_name='price_recalculations')
    op.drop_table('price_recalculations')
    op.drop_index(op.f('exchange_lots_status_idx'), table_name='exchange_lots')
    op.drop_index(op.f('exchange_lots_owner_character_id_idx'), table_name='exchange_lots')
    op.drop_index(op.f('exchange_lots_lot_type_idx'), table_name='exchange_lots')
    op.drop_table('exchange_lots')
    op.drop_index(op.f('economy_scheduler_state_next_run_at_idx'), table_name='economy_scheduler_state')
    op.drop_index(op.f('economy_scheduler_state_locked_until_idx'), table_name='economy_scheduler_state')
    op.drop_index(op.f('economy_scheduler_state_job_name_idx'), table_name='economy_scheduler_state')
    op.drop_table('economy_scheduler_state')
    op.drop_index(op.f('economy_resources_source_type_idx'), table_name='economy_resources')
    op.drop_index(op.f('economy_resources_order_idx'), table_name='economy_resources')
    op.drop_index(op.f('economy_resources_code_idx'), table_name='economy_resources')
    op.drop_index(op.f('economy_resources_category_idx'), table_name='economy_resources')
    op.drop_table('economy_resources')
    # ### end Alembic commands ###
