"""clean_init

Revision ID: 6e62c5758846
Revises: 
Create Date: 2026-10-04 23:55:35.371917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e62c5758846'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_logs',
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.String(length=255), nullable=True),
    sa.Column('character_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('character_id', sa.UUID(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('auth_logs_pkey'))
    )
    op.create_index(op.f('auth_logs_character_id_idx'), 'auth_logs', ['character_id'], unique=False)
    op.create_index(op.f('auth_logs_character_name_idx'), 'auth_logs', ['character_name'], unique=False)
    op.create_index(op.f('auth_logs_ip_address_idx'), 'auth_logs', ['ip_address'], unique=False)
    op.create_index(op.f('auth_logs_user_id_idx'), 'auth_logs', ['user_id'], unique=False)
    op.create_table('new_users_visit',
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('refferal_name', sa.String(length=21), nullable=True),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('new_users_visit_pkey')),
    sa.UniqueConstraint('ip_address', 'character_id', name='uq_ip_char')
    )
    op.create_index(op.f('new_users_visit_ip_address_idx'), 'new_users_visit', ['ip_address'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey'))
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('hashed_refresh_token', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('refresh_tokens_pkey'))
    )
    op.create_index(op.f('refresh_tokens_character_id_idx'), 'refresh_tokens', ['character_id'], unique=False)
    op.create_index(op.f('refresh_tokens_hashed_refresh_token_idx'), 'refresh_tokens', ['hashed_refresh_token'], unique=False)
    op.create_index(op.f('refresh_tokens_user_id_idx'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('session_users_event',
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('fingerprint', sa.String(length=255), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('LOGIN', 'PLAY', 'QUIT', 'REGISTER', 'LOGOUT', name='eventtype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('session_users_event_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_users_event')
    op.drop_index(op.f('refresh_tokens_user_id_idx'), table_name='refresh_tokens')
    op.drop_index(op.f('refresh_tokens_hashed_refresh_token_idx'), table_name='refresh_tokens')
    op.drop_index(op.f('refresh_tokens_character_id_idx'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('new_users_visit_ip_address_idx'), table_name='new_users_visit')
    op.drop_table('new_users_visit')
    op.drop_index(op.f('auth_logs_user_id_idx'), table_name='auth_logs')
    op.drop_index(op.f('auth_logs_ip_address_idx'), table_name='auth_logs')
    op.drop_index(op.f('auth_logs_character_name_idx'), table_name='auth_logs')
    op.drop_index(op.f('auth_logs_character_id_idx'), table_name='auth_logs')
    op.drop_table('auth_logs')
    # ### end Alembic commands ###
