"""clean_init

Revision ID: e91984832841
Revises: 
Create Date: 2026-10-05 00:07:43.352578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e91984832841'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('template_name', sa.String(length=256), nullable=True),
    sa.Column('path', sa.String(length=256), nullable=False),
    sa.Column('creator_user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('content_type', sa.String(length=256), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('files_pkey')),
    sa.UniqueConstraint('path', name=op.f('files_path_key'))
    )
    op.create_index(op.f('files_template_name_idx'), 'files', ['template_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('files_template_name_idx'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
