"""clean_init

Revision ID: cca8d5a07e6b
Revises: 
Create Date: 2026-10-04 23:49:14.581667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca8d5a07e6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderator_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=64), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('moderator_permissions_pkey')),
    sa.UniqueConstraint('user_id', 'permission', name='uq_moderator_user_permission')
    )
    op.create_index(op.f('moderator_permissions_user_id_idx'), 'moderator_permissions', ['user_id'], unique=False)
    op.create_table('user_additional_information',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_of_knowledge', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_additional_information_pkey'))
    )
    op.create_index(op.f('user_additional_information_user_id_idx'), 'user_additional_information', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MODERATOR', 'USER', name='userrole'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('users_email_idx'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('users_email_idx'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('user_additional_information_user_id_idx'), table_name='user_additional_information')
    op.drop_table('user_additional_information')
    op.drop_index(op.f('moderator_permissions_user_id_idx'), table_name='moderator_permissions')
    op.drop_table('moderator_permissions')
    # ### end Alembic commands ###
