"""clean_init

Revision ID: 4c83472f6dba
Revises: 
Create Date: 2026-10-04 23:51:05.045017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c83472f6dba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('owner_character_id', sa.UUID(), nullable=False),
    sa.Column('max_count_characters', sa.Integer(), nullable=False),
    sa.Column('is_send_notifications', sa.Boolean(), nullable=True),
    sa.Column('is_receive_notifications', sa.Boolean(), nullable=True),
    sa.Column('is_block_send_mails', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_pkey')),
    sa.UniqueConstraint('name', 'owner_character_id', name='uq_name_character_owner')
    )
    op.create_index(op.f('categories_owner_character_id_idx'), 'categories', ['owner_character_id'], unique=False)
    op.create_table('chat_ignores',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('ignored_character_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('character_id != ignored_character_id', name=op.f('chat_ignores_ck_character_not_equal_ignored_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_ignores_pkey')),
    sa.UniqueConstraint('character_id', 'ignored_character_id', name='uq_character_ignored_character')
    )
    op.create_index(op.f('chat_ignores_character_id_idx'), 'chat_ignores', ['character_id'], unique=False)
    op.create_index(op.f('chat_ignores_ignored_character_id_idx'), 'chat_ignores', ['ignored_character_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('sender_name', sa.String(length=21), nullable=True),
    sa.Column('message_type', sa.Enum('SYSTEM_GLOBAL', 'SYSTEM_CREATE_CHARACTER', 'SYSTEM_PLAY_CHARACTER', 'SYSTEM_PRIVATE', 'IGNORE', name='messagetype'), nullable=True),
    sa.Column('room', sa.String(length=256), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('target_user_ids', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('target_user_names', sa.ARRAY(sa.String(length=21)), nullable=True),
    sa.Column('is_trade', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_index(op.f('chat_messages_is_trade_idx'), 'chat_messages', ['is_trade'], unique=False)
    op.create_index(op.f('chat_messages_message_type_idx'), 'chat_messages', ['message_type'], unique=False)
    op.create_index(op.f('chat_messages_room_idx'), 'chat_messages', ['room'], unique=False)
    op.create_index(op.f('chat_messages_sender_id_idx'), 'chat_messages', ['sender_id'], unique=False)
    op.create_table('chat_settings',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('chat_enabled', sa.Boolean(), nullable=False),
    sa.Column('clan_chat_is_blue', sa.Boolean(), nullable=False),
    sa.Column('system_italic', sa.Boolean(), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('filter_only_me_and_my', sa.Boolean(), nullable=False),
    sa.Column('filter_system_messages', sa.Boolean(), nullable=False),
    sa.Column('filter_trade_messages', sa.Boolean(), nullable=False),
    sa.Column('filter_location_messages', sa.Boolean(), nullable=False),
    sa.Column('show_journal', sa.Boolean(), nullable=False),
    sa.Column('show_bell', sa.Boolean(), nullable=False),
    sa.Column('show_translit', sa.Boolean(), nullable=False),
    sa.Column('show_lastic', sa.Boolean(), nullable=False),
    sa.Column('show_clear_screen', sa.Boolean(), nullable=False),
    sa.Column('show_trade_messages_button', sa.Boolean(), nullable=False),
    sa.Column('sound_general_chat', sa.Boolean(), nullable=False),
    sa.Column('sound_private_message', sa.Boolean(), nullable=False),
    sa.Column('sound_clan_battle', sa.Boolean(), nullable=False),
    sa.Column('sound_battle_start', sa.Boolean(), nullable=False),
    sa.Column('sound_timeout', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_settings_pkey'))
    )
    op.create_index(op.f('chat_settings_character_id_idx'), 'chat_settings', ['character_id'], unique=True)
    op.create_table('favorite_bells',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('code_bell', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('favorite_bells_pkey'))
    )
    op.create_index(op.f('favorite_bells_character_id_idx'), 'favorite_bells', ['character_id'], unique=False)
    op.create_table('mail_messages',
    sa.Column('from_character_name', sa.String(length=256), nullable=True),
    sa.Column('from_character_id', sa.UUID(), nullable=True),
    sa.Column('sender_status', sa.Enum('USER', 'SYSTEM', name='senderstatus'), nullable=False),
    sa.Column('to_character_name', sa.String(length=256), nullable=False),
    sa.Column('to_character_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_active_recipient', sa.Boolean(), nullable=False),
    sa.Column('is_active_sender', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('mail_messages_pkey'))
    )
    op.create_index(op.f('mail_messages_from_character_id_idx'), 'mail_messages', ['from_character_id'], unique=False)
    op.create_index(op.f('mail_messages_is_active_recipient_idx'), 'mail_messages', ['is_active_recipient'], unique=False)
    op.create_index(op.f('mail_messages_is_active_sender_idx'), 'mail_messages', ['is_active_sender'], unique=False)
    op.create_index(op.f('mail_messages_is_read_idx'), 'mail_messages', ['is_read'], unique=False)
    op.create_index(op.f('mail_messages_sender_status_idx'), 'mail_messages', ['sender_status'], unique=False)
    op.create_index(op.f('mail_messages_to_character_id_idx'), 'mail_messages', ['to_character_id'], unique=False)
    op.create_table('mail_settings',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('is_block_send_mails', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('mail_settings_pkey'))
    )
    op.create_index(op.f('mail_settings_character_id_idx'), 'mail_settings', ['character_id'], unique=True)
    op.create_table('categories_characters',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('categories_characters_category_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('categories_characters_pkey')),
    sa.UniqueConstraint('category_id', 'character_id', name='uq_category_character')
    )
    op.create_index(op.f('categories_characters_category_id_idx'), 'categories_characters', ['category_id'], unique=False)
    op.create_index(op.f('categories_characters_character_id_idx'), 'categories_characters', ['character_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('categories_characters_character_id_idx'), table_name='categories_characters')
    op.drop_index(op.f('categories_characters_category_id_idx'), table_name='categories_characters')
    op.drop_table('categories_characters')
    op.drop_index(op.f('mail_settings_character_id_idx'), table_name='mail_settings')
    op.drop_table('mail_settings')
    op.drop_index(op.f('mail_messages_to_character_id_idx'), table_name='mail_messages')
    op.drop_index(op.f('mail_messages_sender_status_idx'), table_name='mail_messages')
    op.drop_index(op.f('mail_messages_is_read_idx'), table_name='mail_messages')
    op.drop_index(op.f('mail_messages_is_active_sender_idx'), table_name='mail_messages')
    op.drop_index(op.f('mail_messages_is_active_recipient_idx'), table_name='mail_messages')
    op.drop_index(op.f('mail_messages_from_character_id_idx'), table_name='mail_messages')
    op.drop_table('mail_messages')
    op.drop_index(op.f('favorite_bells_character_id_idx'), table_name='favorite_bells')
    op.drop_table('favorite_bells')
    op.drop_index(op.f('chat_settings_character_id_idx'), table_name='chat_settings')
    op.drop_table('chat_settings')
    op.drop_index(op.f('chat_messages_sender_id_idx'), table_name='chat_messages')
    op.drop_index(op.f('chat_messages_room_idx'), table_name='chat_messages')
    op.drop_index(op.f('chat_messages_message_type_idx'), table_name='chat_messages')
    op.drop_index(op.f('chat_messages_is_trade_idx'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('chat_ignores_ignored_character_id_idx'), table_name='chat_ignores')
    op.drop_index(op.f('chat_ignores_character_id_idx'), table_name='chat_ignores')
    op.drop_table('chat_ignores')
    op.drop_index(op.f('categories_owner_character_id_idx'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
