"""clean_init

Revision ID: 7add95f54f83
Revises: 
Create Date: 2026-10-04 23:25:40.849533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7add95f54f83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('admin_user_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_logs_pkey'))
    )
    op.create_index(op.f('admin_logs_admin_user_id_idx'), 'admin_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('admin_logs_character_id_idx'), 'admin_logs', ['character_id'], unique=False)
    op.create_table('buildings',
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('city_trading_location_slug', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('buildings_pkey'))
    )
    op.create_index(op.f('buildings_city_trading_location_slug_idx'), 'buildings', ['city_trading_location_slug'], unique=True)
    op.create_index(op.f('buildings_location_slug_idx'), 'buildings', ['location_slug'], unique=True)
    op.create_table('character_city_trade_stats',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('character_city_trade_stats_pkey')),
    sa.UniqueConstraint('character_id', 'location_slug', name='uq_character_city_trade_location')
    )
    op.create_index(op.f('character_city_trade_stats_character_id_idx'), 'character_city_trade_stats', ['character_id'], unique=False)
    op.create_index(op.f('character_city_trade_stats_location_slug_idx'), 'character_city_trade_stats', ['location_slug'], unique=False)
    op.create_table('characters_locations_stats',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('add_chance', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('characters_locations_stats_pkey')),
    sa.UniqueConstraint('character_id', 'location_slug', name='uq_character_location')
    )
    op.create_index(op.f('characters_locations_stats_character_id_idx'), 'characters_locations_stats', ['character_id'], unique=False)
    op.create_index(op.f('characters_locations_stats_location_slug_idx'), 'characters_locations_stats', ['location_slug'], unique=False)
    op.create_table('city_trading_shop',
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=True),
    sa.Column('character_name', sa.String(length=21), nullable=True),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('description', sa.String(length=75), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('current_capacity', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=True),
    sa.Column('end_license', sa.DateTime(timezone=True), nullable=True),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('city_trading_shop_pkey')),
    sa.UniqueConstraint('location_slug', 'character_id', name='uq_location_character'),
    sa.UniqueConstraint('location_slug', 'number', name='uq_location_shop_number')
    )
    op.create_index(op.f('city_trading_shop_end_license_idx'), 'city_trading_shop', ['end_license'], unique=False)
    op.create_index(op.f('city_trading_shop_location_slug_idx'), 'city_trading_shop', ['location_slug'], unique=False)
    op.create_table('city_trading_shop_buy_settings',
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('min_level', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('city_trading_shop_buy_settings_pkey'))
    )
    op.create_index(op.f('city_trading_shop_buy_settings_location_slug_idx'), 'city_trading_shop_buy_settings', ['location_slug'], unique=False)
    op.create_table('city_trading_shop_settings',
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('price_up_level', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('city_trading_shop_settings_pkey'))
    )
    op.create_index(op.f('city_trading_shop_settings_level_idx'), 'city_trading_shop_settings', ['level'], unique=False)
    op.create_index(op.f('city_trading_shop_settings_location_slug_idx'), 'city_trading_shop_settings', ['location_slug'], unique=False)
    op.create_table('crafting_licenses',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('crafting_licenses_pkey')),
    sa.UniqueConstraint('character_id', 'location_slug', name='uq_character_crafting_license'),
    sa.UniqueConstraint('location_slug', 'number', name='uq_location_license_number')
    )
    op.create_index(op.f('crafting_licenses_character_id_idx'), 'crafting_licenses', ['character_id'], unique=False)
    op.create_table('deals',
    sa.Column('initiator_character_id', sa.UUID(), nullable=False),
    sa.Column('partner_character_id', sa.UUID(), nullable=False),
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETING', 'COMPLETED', 'CANCELLED', 'EXPIRED', name='dealstatus'), nullable=False),
    sa.Column('initiator_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('partner_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_character_id', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('initiator_character_id <> partner_character_id', name=op.f('deals_different_participants_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('deals_pkey'))
    )
    op.create_index(op.f('deals_cancelled_by_character_id_idx'), 'deals', ['cancelled_by_character_id'], unique=False)
    op.create_index(op.f('deals_expires_at_idx'), 'deals', ['expires_at'], unique=False)
    op.create_index(op.f('deals_initiator_character_id_idx'), 'deals', ['initiator_character_id'], unique=False)
    op.create_index(op.f('deals_location_slug_idx'), 'deals', ['location_slug'], unique=False)
    op.create_index(op.f('deals_partner_character_id_idx'), 'deals', ['partner_character_id'], unique=False)
    op.create_index(op.f('deals_status_idx'), 'deals', ['status'], unique=False)
    op.create_table('experience_for_level',
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('success_rate_one', sa.Float(), nullable=False),
    sa.Column('success_rate_two', sa.Float(), nullable=False),
    sa.Column('success_rate_three', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('experience_for_level_pkey')),
    sa.UniqueConstraint('experience', name=op.f('experience_for_level_experience_key'))
    )
    op.create_index(op.f('experience_for_level_level_idx'), 'experience_for_level', ['level'], unique=True)
    op.create_table('item_experience_for_level',
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('success_rate_one', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('item_experience_for_level_pkey')),
    sa.UniqueConstraint('experience', name=op.f('item_experience_for_level_experience_key'))
    )
    op.create_index(op.f('item_experience_for_level_level_idx'), 'item_experience_for_level', ['level'], unique=True)
    op.create_table('items',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('item_type', sa.Enum('ELIXIR', 'ANIMAL', 'OIL', 'FISH', 'FURNITURE', 'WEAPON', 'SHIELD', 'HELMET', 'ARMOR', 'GAUNTLETS', 'GLOVES', 'LEGGINGS', 'BOOTS', 'CLOAK', 'AMULET', 'PENDANT', 'RING', 'KIT', name='itemtype'), nullable=False),
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('race', sa.Enum('HUMAN', 'ELF', 'ORC', name='race'), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ability_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('craft_stages', sa.Integer(), nullable=True),
    sa.Column('craft_experience', sa.Integer(), nullable=True),
    sa.Column('min_shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('max_shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('min_output_quantity', sa.Integer(), nullable=True),
    sa.Column('max_output_quantity', sa.Integer(), nullable=True),
    sa.Column('minimal_level', sa.Integer(), nullable=False),
    sa.Column('is_stackable', sa.Boolean(), nullable=False),
    sa.Column('can_sell', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('items_pkey'))
    )
    op.create_index(op.f('items_location_slug_idx'), 'items', ['location_slug'], unique=False)
    op.create_index(op.f('items_slug_idx'), 'items', ['slug'], unique=True)
    op.create_index('ix_items_ability_parameters_gin', 'items', ['ability_parameters'], unique=False, postgresql_using='gin')
    op.create_index('ix_items_parameters_gin', 'items', ['parameters'], unique=False, postgresql_using='gin')
    op.create_table('location_settings',
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('up_chance_for_unluck', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('location_settings_pkey'))
    )
    op.create_index(op.f('location_settings_location_slug_idx'), 'location_settings', ['location_slug'], unique=True)
    op.create_table('resources',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('resources_pkey'))
    )
    op.create_index(op.f('resources_category_idx'), 'resources', ['category'], unique=False)
    op.create_index(op.f('resources_serial_number_idx'), 'resources', ['serial_number'], unique=True)
    op.create_index(op.f('resources_slug_idx'), 'resources', ['slug'], unique=True)
    op.create_table('shop_number_counters',
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('last_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('location_slug', name=op.f('shop_number_counters_pkey'))
    )
    op.create_table('trade_licenses',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('trade_licenses_pkey'))
    )
    op.create_index(op.f('trade_licenses_character_id_idx'), 'trade_licenses', ['character_id'], unique=True)
    op.create_index(op.f('trade_licenses_end_date_idx'), 'trade_licenses', ['end_date'], unique=False)
    op.create_table('character_recipes',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('item_slug', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_slug'], ['items.slug'], name=op.f('character_recipes_item_slug_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('character_recipes_pkey'))
    )
    op.create_index(op.f('character_recipes_character_id_idx'), 'character_recipes', ['character_id'], unique=False)
    op.create_index(op.f('character_recipes_item_slug_idx'), 'character_recipes', ['item_slug'], unique=False)
    op.create_index(op.f('character_recipes_quantity_idx'), 'character_recipes', ['quantity'], unique=False)
    op.create_table('character_resource_operations',
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('resource_slug', sa.String(length=128), nullable=False),
    sa.Column('operation_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_slug'], ['resources.slug'], name=op.f('character_resource_operations_resource_slug_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('character_resource_operations_pkey'))
    )
    op.create_index(op.f('character_resource_operations_character_id_idx'), 'character_resource_operations', ['character_id'], unique=False)
    op.create_index(op.f('character_resource_operations_operation_id_idx'), 'character_resource_operations', ['operation_id'], unique=True)
    op.create_index(op.f('character_resource_operations_resource_slug_idx'), 'character_resource_operations', ['resource_slug'], unique=False)
    op.create_table('character_resources',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('resource_slug', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_slug'], ['resources.slug'], name=op.f('character_resources_resource_slug_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('character_resources_pkey')),
    sa.UniqueConstraint('character_id', 'resource_slug', name='uq_character_resource')
    )
    op.create_index(op.f('character_resources_character_id_idx'), 'character_resources', ['character_id'], unique=False)
    op.create_index(op.f('character_resources_resource_slug_idx'), 'character_resources', ['resource_slug'], unique=False)
    op.create_table('character_start_creating_items',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('item_slug', sa.String(length=128), nullable=False),
    sa.Column('craft_stage', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_slug'], ['items.slug'], name=op.f('character_start_creating_items_item_slug_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('character_start_creating_items_pkey'))
    )
    op.create_index(op.f('character_start_creating_items_character_id_idx'), 'character_start_creating_items', ['character_id'], unique=False)
    op.create_index(op.f('character_start_creating_items_item_slug_idx'), 'character_start_creating_items', ['item_slug'], unique=False)
    op.create_table('deal_ledger_operations',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('operation_kind', sa.Enum('ESCROW_HOLD', 'ESCROW_RELEASE', 'TRANSFER', 'TAX', 'COMPENSATION', name='dealledgeroperationkind'), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('counterparty_id', sa.UUID(), nullable=True),
    sa.Column('currency', sa.Enum('DUCATS', 'GOLD', name='dealcurrency'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPLIED', 'COMPENSATED', 'FAILED', name='dealledgeroperationstatus'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('deal_ledger_operations_deal_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('deal_ledger_operations_pkey'))
    )
    op.create_index(op.f('deal_ledger_operations_character_id_idx'), 'deal_ledger_operations', ['character_id'], unique=False)
    op.create_index(op.f('deal_ledger_operations_counterparty_id_idx'), 'deal_ledger_operations', ['counterparty_id'], unique=False)
    op.create_index(op.f('deal_ledger_operations_currency_idx'), 'deal_ledger_operations', ['currency'], unique=False)
    op.create_index(op.f('deal_ledger_operations_deal_id_idx'), 'deal_ledger_operations', ['deal_id'], unique=False)
    op.create_index(op.f('deal_ledger_operations_operation_id_idx'), 'deal_ledger_operations', ['operation_id'], unique=True)
    op.create_index(op.f('deal_ledger_operations_operation_kind_idx'), 'deal_ledger_operations', ['operation_kind'], unique=False)
    op.create_index(op.f('deal_ledger_operations_status_idx'), 'deal_ledger_operations', ['status'], unique=False)
    op.create_table('deal_offers',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('ducats_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('ducats_escrowed', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('gold_amount', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('gold_escrowed', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confirmed_revision', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ducats_amount >= 0', name=op.f('deal_offers_ck_deal_offers_ducats_amount_positive_check')),
    sa.CheckConstraint('ducats_escrowed >= 0', name=op.f('deal_offers_ck_deal_offers_ducats_escrowed_positive_check')),
    sa.CheckConstraint('gold_amount >= 0', name=op.f('deal_offers_ck_deal_offers_gold_amount_positive_check')),
    sa.CheckConstraint('gold_escrowed >= 0', name=op.f('deal_offers_ck_deal_offers_gold_escrowed_positive_check')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('deal_offers_deal_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('deal_offers_pkey')),
    sa.UniqueConstraint('deal_id', 'character_id', name='uq_deal_offer_character')
    )
    op.create_index(op.f('deal_offers_character_id_idx'), 'deal_offers', ['character_id'], unique=False)
    op.create_index(op.f('deal_offers_deal_id_idx'), 'deal_offers', ['deal_id'], unique=False)
    op.create_table('inventory_items',
    sa.Column('character_id', sa.UUID(), nullable=True),
    sa.Column('shop_id', sa.UUID(), nullable=True),
    sa.Column('deal_id', sa.UUID(), nullable=True),
    sa.Column('item_slug', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('expired_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=True),
    sa.Column('wear', sa.Integer(), nullable=True),
    sa.Column('item_binding_type', sa.Enum('NONE', 'CHARACTER', 'CLAN', name='itembindingtype'), server_default='NONE', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(character_id IS NOT NULL AND shop_id IS NULL) OR (character_id IS NULL AND shop_id IS NOT NULL)', name=op.f('inventory_items_check_character_or_shop_check')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('inventory_items_deal_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_slug'], ['items.slug'], name=op.f('inventory_items_item_slug_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shop_id'], ['city_trading_shop.id'], name=op.f('inventory_items_shop_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_items_pkey'))
    )
    op.create_index(op.f('inventory_items_character_id_idx'), 'inventory_items', ['character_id'], unique=False)
    op.create_index(op.f('inventory_items_deal_id_idx'), 'inventory_items', ['deal_id'], unique=False)
    op.create_index(op.f('inventory_items_expired_date_idx'), 'inventory_items', ['expired_date'], unique=False)
    op.create_index(op.f('inventory_items_item_slug_idx'), 'inventory_items', ['item_slug'], unique=False)
    op.create_index(op.f('inventory_items_shop_id_idx'), 'inventory_items', ['shop_id'], unique=False)
    op.create_table('item_components',
    sa.Column('item_slug', sa.String(length=128), nullable=False),
    sa.Column('resource_slug', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_slug'], ['items.slug'], name=op.f('item_components_item_slug_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_slug'], ['resources.slug'], name=op.f('item_components_resource_slug_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_components_pkey'))
    )
    op.create_index(op.f('item_components_item_slug_idx'), 'item_components', ['item_slug'], unique=False)
    op.create_index(op.f('item_components_resource_slug_idx'), 'item_components', ['resource_slug'], unique=False)
    op.create_table('item_prices',
    sa.Column('item_slug', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['item_slug'], ['items.slug'], name=op.f('item_prices_item_slug_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('item_prices_pkey')),
    sa.UniqueConstraint('item_slug', 'quantity', name='uq_item_quantity')
    )
    op.create_index(op.f('item_prices_item_slug_idx'), 'item_prices', ['item_slug'], unique=False)
    op.create_index(op.f('item_prices_quantity_idx'), 'item_prices', ['quantity'], unique=False)
    op.create_table('items_creating_actions',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finish_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'DONE', 'CANCELLED', name='itemcreatingstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('result_status', sa.Enum('SUCCESS', 'FAILURE', name='resultstatus'), nullable=True),
    sa.Column('recived_item_slug', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('craft_stage', sa.Integer(), nullable=False),
    sa.Column('lost_resource', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_slug'], ['buildings.location_slug'], name=op.f('items_creating_actions_location_slug_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lost_resource'], ['resources.slug'], name=op.f('items_creating_actions_lost_resource_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recived_item_slug'], ['items.slug'], name=op.f('items_creating_actions_recived_item_slug_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('items_creating_actions_pkey'))
    )
    op.create_index(op.f('items_creating_actions_character_id_idx'), 'items_creating_actions', ['character_id'], unique=False)
    op.create_index(op.f('items_creating_actions_location_slug_idx'), 'items_creating_actions', ['location_slug'], unique=False)
    op.create_table('location_resources',
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('resource_slug', sa.String(length=128), nullable=False),
    sa.Column('chance', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Integer(), nullable=False),
    sa.Column('max_amount', sa.Integer(), nullable=False),
    sa.Column('experience_on_resource', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_slug'], ['resources.slug'], name=op.f('location_resources_resource_slug_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('location_resources_pkey')),
    sa.UniqueConstraint('location_slug', 'resource_slug', name='uq_location_resource')
    )
    op.create_index(op.f('location_resources_location_slug_idx'), 'location_resources', ['location_slug'], unique=False)
    op.create_index(op.f('location_resources_resource_slug_idx'), 'location_resources', ['resource_slug'], unique=False)
    op.create_table('mining_actions',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finish_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'DONE', 'CANCELLED', name='miningstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('result_status', sa.Enum('SUCCESS', 'FAILURE', name='resultstatus'), nullable=True),
    sa.Column('recived_resourse_slug', sa.String(length=128), nullable=True),
    sa.Column('count_recived_resource', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recived_resourse_slug'], ['resources.slug'], name=op.f('mining_actions_recived_resourse_slug_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mining_actions_pkey'))
    )
    op.create_index(op.f('mining_actions_character_id_idx'), 'mining_actions', ['character_id'], unique=False)
    op.create_index(op.f('mining_actions_location_slug_idx'), 'mining_actions', ['location_slug'], unique=False)
    op.create_table('monster_on_location',
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('standart_monster_name', sa.String(length=128), nullable=False),
    sa.Column('standart_monster_skin_slug', sa.String(length=128), nullable=False),
    sa.Column('improved_monster_name', sa.String(length=128), nullable=False),
    sa.Column('improved_monster_skin_slug', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['improved_monster_skin_slug'], ['resources.slug'], name=op.f('monster_on_location_improved_monster_skin_slug_fkey')),
    sa.ForeignKeyConstraint(['standart_monster_skin_slug'], ['resources.slug'], name=op.f('monster_on_location_standart_monster_skin_slug_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('monster_on_location_pkey'))
    )
    op.create_index(op.f('monster_on_location_improved_monster_name_idx'), 'monster_on_location', ['improved_monster_name'], unique=True)
    op.create_index(op.f('monster_on_location_improved_monster_skin_slug_idx'), 'monster_on_location', ['improved_monster_skin_slug'], unique=True)
    op.create_index(op.f('monster_on_location_location_slug_idx'), 'monster_on_location', ['location_slug'], unique=True)
    op.create_index(op.f('monster_on_location_standart_monster_name_idx'), 'monster_on_location', ['standart_monster_name'], unique=True)
    op.create_index(op.f('monster_on_location_standart_monster_skin_slug_idx'), 'monster_on_location', ['standart_monster_skin_slug'], unique=True)
    op.create_table('sale_history',
    sa.Column('shop_id', sa.UUID(), nullable=True),
    sa.Column('seller_character_id', sa.UUID(), nullable=False),
    sa.Column('buyer_character_id', sa.UUID(), nullable=False),
    sa.Column('buyer_name', sa.String(length=21), nullable=False),
    sa.Column('item_slug', sa.String(length=128), nullable=False),
    sa.Column('item_name', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['city_trading_shop.id'], name=op.f('sale_history_shop_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('sale_history_pkey'))
    )
    op.create_index('ix_sale_history_seller', 'sale_history', ['seller_character_id', 'created_at'], unique=False)
    op.create_index(op.f('sale_history_item_slug_idx'), 'sale_history', ['item_slug'], unique=False)
    op.create_index(op.f('sale_history_location_slug_idx'), 'sale_history', ['location_slug'], unique=False)
    op.create_index(op.f('sale_history_seller_character_id_idx'), 'sale_history', ['seller_character_id'], unique=False)
    op.create_index(op.f('sale_history_shop_id_idx'), 'sale_history', ['shop_id'], unique=False)
    op.create_table('character_equipment',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.Enum('HEAD', 'CHEST', 'HANDS', 'GLOVES', 'LEGS', 'FEET', 'WEAPON', 'SHIELD', 'CLOAK', 'AMULET', 'PENDANT', 'RING1', 'RING2', 'RING3', name='equipmentslot'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('character_equipment_inventory_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('character_equipment_pkey')),
    sa.UniqueConstraint('character_id', 'slot', name='uq_character_equipment_slot')
    )
    op.create_index(op.f('character_equipment_character_id_idx'), 'character_equipment', ['character_id'], unique=False)
    op.create_index(op.f('character_equipment_inventory_item_id_idx'), 'character_equipment', ['inventory_item_id'], unique=True)
    op.create_table('deal_items',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('owner_character_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Enum('RESOURCE', 'INVENTORY_ITEM', name='dealassettype'), nullable=False),
    sa.Column('resource_slug', sa.String(length=128), nullable=True),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('item_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(asset_type = 'RESOURCE' AND resource_slug IS NOT NULL) OR (asset_type = 'INVENTORY_ITEM' AND inventory_item_id IS NOT NULL)", name=op.f('deal_items_asset_type_matches_reference_check')),
    sa.CheckConstraint('(resource_slug IS NOT NULL AND inventory_item_id IS NULL) OR (resource_slug IS NULL AND inventory_item_id IS NOT NULL)', name=op.f('deal_items_resource_xor_inventory_item_check')),
    sa.CheckConstraint('amount > 0', name=op.f('deal_items_positive_amount_check')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('deal_items_deal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('deal_items_inventory_item_id_fkey')),
    sa.ForeignKeyConstraint(['offer_id'], ['deal_offers.id'], name=op.f('deal_items_offer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_slug'], ['resources.slug'], name=op.f('deal_items_resource_slug_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deal_items_pkey'))
    )
    op.create_index(op.f('deal_items_asset_type_idx'), 'deal_items', ['asset_type'], unique=False)
    op.create_index(op.f('deal_items_deal_id_idx'), 'deal_items', ['deal_id'], unique=False)
    op.create_index(op.f('deal_items_inventory_item_id_idx'), 'deal_items', ['inventory_item_id'], unique=False)
    op.create_index(op.f('deal_items_offer_id_idx'), 'deal_items', ['offer_id'], unique=False)
    op.create_index(op.f('deal_items_owner_character_id_idx'), 'deal_items', ['owner_character_id'], unique=False)
    op.create_index(op.f('deal_items_resource_slug_idx'), 'deal_items', ['resource_slug'], unique=False)
    op.create_table('sale_inventory_items',
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], name=op.f('sale_inventory_items_inventory_item_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sale_inventory_items_pkey'))
    )
    op.create_index(op.f('sale_inventory_items_inventory_item_id_idx'), 'sale_inventory_items', ['inventory_item_id'], unique=True)
    op.create_table('deal_resource_reservations',
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('deal_item_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('resource_slug', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RELEASED', 'TRANSFERRED', name='resourcereservationstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('deal_resource_reservations_positive_amount_check')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('deal_resource_reservations_deal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_item_id'], ['deal_items.id'], name=op.f('deal_resource_reservations_deal_item_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_slug'], ['resources.slug'], name=op.f('deal_resource_reservations_resource_slug_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('deal_resource_reservations_pkey'))
    )
    op.create_index(op.f('deal_resource_reservations_character_id_idx'), 'deal_resource_reservations', ['character_id'], unique=False)
    op.create_index(op.f('deal_resource_reservations_deal_id_idx'), 'deal_resource_reservations', ['deal_id'], unique=False)
    op.create_index(op.f('deal_resource_reservations_deal_item_id_idx'), 'deal_resource_reservations', ['deal_item_id'], unique=True)
    op.create_index(op.f('deal_resource_reservations_resource_slug_idx'), 'deal_resource_reservations', ['resource_slug'], unique=False)
    op.create_index(op.f('deal_resource_reservations_status_idx'), 'deal_resource_reservations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('deal_resource_reservations_status_idx'), table_name='deal_resource_reservations')
    op.drop_index(op.f('deal_resource_reservations_resource_slug_idx'), table_name='deal_resource_reservations')
    op.drop_index(op.f('deal_resource_reservations_deal_item_id_idx'), table_name='deal_resource_reservations')
    op.drop_index(op.f('deal_resource_reservations_deal_id_idx'), table_name='deal_resource_reservations')
    op.drop_index(op.f('deal_resource_reservations_character_id_idx'), table_name='deal_resource_reservations')
    op.drop_table('deal_resource_reservations')
    op.drop_index(op.f('sale_inventory_items_inventory_item_id_idx'), table_name='sale_inventory_items')
    op.drop_table('sale_inventory_items')
    op.drop_index(op.f('deal_items_resource_slug_idx'), table_name='deal_items')
    op.drop_index(op.f('deal_items_owner_character_id_idx'), table_name='deal_items')
    op.drop_index(op.f('deal_items_offer_id_idx'), table_name='deal_items')
    op.drop_index(op.f('deal_items_inventory_item_id_idx'), table_name='deal_items')
    op.drop_index(op.f('deal_items_deal_id_idx'), table_name='deal_items')
    op.drop_index(op.f('deal_items_asset_type_idx'), table_name='deal_items')
    op.drop_table('deal_items')
    op.drop_index(op.f('character_equipment_inventory_item_id_idx'), table_name='character_equipment')
    op.drop_index(op.f('character_equipment_character_id_idx'), table_name='character_equipment')
    op.drop_table('character_equipment')
    op.drop_index(op.f('sale_history_shop_id_idx'), table_name='sale_history')
    op.drop_index(op.f('sale_history_seller_character_id_idx'), table_name='sale_history')
    op.drop_index(op.f('sale_history_location_slug_idx'), table_name='sale_history')
    op.drop_index(op.f('sale_history_item_slug_idx'), table_name='sale_history')
    op.drop_index('ix_sale_history_seller', table_name='sale_history')
    op.drop_table('sale_history')
    op.drop_index(op.f('monster_on_location_standart_monster_skin_slug_idx'), table_name='monster_on_location')
    op.drop_index(op.f('monster_on_location_standart_monster_name_idx'), table_name='monster_on_location')
    op.drop_index(op.f('monster_on_location_location_slug_idx'), table_name='monster_on_location')
    op.drop_index(op.f('monster_on_location_improved_monster_skin_slug_idx'), table_name='monster_on_location')
    op.drop_index(op.f('monster_on_location_improved_monster_name_idx'), table_name='monster_on_location')
    op.drop_table('monster_on_location')
    op.drop_index(op.f('mining_actions_location_slug_idx'), table_name='mining_actions')
    op.drop_index(op.f('mining_actions_character_id_idx'), table_name='mining_actions')
    op.drop_table('mining_actions')
    op.drop_index(op.f('location_resources_resource_slug_idx'), table_name='location_resources')
    op.drop_index(op.f('location_resources_location_slug_idx'), table_name='location_resources')
    op.drop_table('location_resources')
    op.drop_index(op.f('items_creating_actions_location_slug_idx'), table_name='items_creating_actions')
    op.drop_index(op.f('items_creating_actions_character_id_idx'), table_name='items_creating_actions')
    op.drop_table('items_creating_actions')
    op.drop_index(op.f('item_prices_quantity_idx'), table_name='item_prices')
    op.drop_index(op.f('item_prices_item_slug_idx'), table_name='item_prices')
    op.drop_table('item_prices')
    op.drop_index(op.f('item_components_resource_slug_idx'), table_name='item_components')
    op.drop_index(op.f('item_components_item_slug_idx'), table_name='item_components')
    op.drop_table('item_components')
    op.drop_index(op.f('inventory_items_shop_id_idx'), table_name='inventory_items')
    op.drop_index(op.f('inventory_items_item_slug_idx'), table_name='inventory_items')
    op.drop_index(op.f('inventory_items_expired_date_idx'), table_name='inventory_items')
    op.drop_index(op.f('inventory_items_deal_id_idx'), table_name='inventory_items')
    op.drop_index(op.f('inventory_items_character_id_idx'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index(op.f('deal_offers_deal_id_idx'), table_name='deal_offers')
    op.drop_index(op.f('deal_offers_character_id_idx'), table_name='deal_offers')
    op.drop_table('deal_offers')
    op.drop_index(op.f('deal_ledger_operations_status_idx'), table_name='deal_ledger_operations')
    op.drop_index(op.f('deal_ledger_operations_operation_kind_idx'), table_name='deal_ledger_operations')
    op.drop_index(op.f('deal_ledger_operations_operation_id_idx'), table_name='deal_ledger_operations')
    op.drop_index(op.f('deal_ledger_operations_deal_id_idx'), table_name='deal_ledger_operations')
    op.drop_index(op.f('deal_ledger_operations_currency_idx'), table_name='deal_ledger_operations')
    op.drop_index(op.f('deal_ledger_operations_counterparty_id_idx'), table_name='deal_ledger_operations')
    op.drop_index(op.f('deal_ledger_operations_character_id_idx'), table_name='deal_ledger_operations')
    op.drop_table('deal_ledger_operations')
    op.drop_index(op.f('character_start_creating_items_item_slug_idx'), table_name='character_start_creating_items')
    op.drop_index(op.f('character_start_creating_items_character_id_idx'), table_name='character_start_creating_items')
    op.drop_table('character_start_creating_items')
    op.drop_index(op.f('character_resources_resource_slug_idx'), table_name='character_resources')
    op.drop_index(op.f('character_resources_character_id_idx'), table_name='character_resources')
    op.drop_table('character_resources')
    op.drop_index(op.f('character_resource_operations_resource_slug_idx'), table_name='character_resource_operations')
    op.drop_index(op.f('character_resource_operations_operation_id_idx'), table_name='character_resource_operations')
    op.drop_index(op.f('character_resource_operations_character_id_idx'), table_name='character_resource_operations')
    op.drop_table('character_resource_operations')
    op.drop_index(op.f('character_recipes_quantity_idx'), table_name='character_recipes')
    op.drop_index(op.f('character_recipes_item_slug_idx'), table_name='character_recipes')
    op.drop_index(op.f('character_recipes_character_id_idx'), table_name='character_recipes')
    op.drop_table('character_recipes')
    op.drop_index(op.f('trade_licenses_end_date_idx'), table_name='trade_licenses')
    op.drop_index(op.f('trade_licenses_character_id_idx'), table_name='trade_licenses')
    op.drop_table('trade_licenses')
    op.drop_table('shop_number_counters')
    op.drop_index(op.f('resources_slug_idx'), table_name='resources')
    op.drop_index(op.f('resources_serial_number_idx'), table_name='resources')
    op.drop_index(op.f('resources_category_idx'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('location_settings_location_slug_idx'), table_name='location_settings')
    op.drop_table('location_settings')
    op.drop_index('ix_items_parameters_gin', table_name='items', postgresql_using='gin')
    op.drop_index('ix_items_ability_parameters_gin', table_name='items', postgresql_using='gin')
    op.drop_index(op.f('items_slug_idx'), table_name='items')
    op.drop_index(op.f('items_location_slug_idx'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('item_experience_for_level_level_idx'), table_name='item_experience_for_level')
    op.drop_table('item_experience_for_level')
    op.drop_index(op.f('experience_for_level_level_idx'), table_name='experience_for_level')
    op.drop_table('experience_for_level')
    op.drop_index(op.f('deals_status_idx'), table_name='deals')
    op.drop_index(op.f('deals_partner_character_id_idx'), table_name='deals')
    op.drop_index(op.f('deals_location_slug_idx'), table_name='deals')
    op.drop_index(op.f('deals_initiator_character_id_idx'), table_name='deals')
    op.drop_index(op.f('deals_expires_at_idx'), table_name='deals')
    op.drop_index(op.f('deals_cancelled_by_character_id_idx'), table_name='deals')
    op.drop_table('deals')
    op.drop_index(op.f('crafting_licenses_character_id_idx'), table_name='crafting_licenses')
    op.drop_table('crafting_licenses')
    op.drop_index(op.f('city_trading_shop_settings_location_slug_idx'), table_name='city_trading_shop_settings')
    op.drop_index(op.f('city_trading_shop_settings_level_idx'), table_name='city_trading_shop_settings')
    op.drop_table('city_trading_shop_settings')
    op.drop_index(op.f('city_trading_shop_buy_settings_location_slug_idx'), table_name='city_trading_shop_buy_settings')
    op.drop_table('city_trading_shop_buy_settings')
    op.drop_index(op.f('city_trading_shop_location_slug_idx'), table_name='city_trading_shop')
    op.drop_index(op.f('city_trading_shop_end_license_idx'), table_name='city_trading_shop')
    op.drop_table('city_trading_shop')
    op.drop_index(op.f('characters_locations_stats_location_slug_idx'), table_name='characters_locations_stats')
    op.drop_index(op.f('characters_locations_stats_character_id_idx'), table_name='characters_locations_stats')
    op.drop_table('characters_locations_stats')
    op.drop_index(op.f('character_city_trade_stats_location_slug_idx'), table_name='character_city_trade_stats')
    op.drop_index(op.f('character_city_trade_stats_character_id_idx'), table_name='character_city_trade_stats')
    op.drop_table('character_city_trade_stats')
    op.drop_index(op.f('buildings_location_slug_idx'), table_name='buildings')
    op.drop_index(op.f('buildings_city_trading_location_slug_idx'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('admin_logs_character_id_idx'), table_name='admin_logs')
    op.drop_index(op.f('admin_logs_admin_user_id_idx'), table_name='admin_logs')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
