export const config = {
  API_BASE_URL: import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080/api/auth',
  VISIT_API_BASE_URL: import.meta.env.VITE_VISIT_API_BASE_URL || 'http://localhost:8080/api/visits',
  CHARACTER_API_BASE_URL: import.meta.env.VITE_CHARACTER_API_BASE_URL || 'http://localhost:8082/api/characters',
  CURRENCY_API_BASE_URL: import.meta.env.VITE_CURRENCY_API_BASE_URL || 'http://localhost:8082/api/slots',
  NOTEBOOK_API_BASE_URL: import.meta.env.VITE_NOTEBOOK_API_BASE_URL || 'http://localhost:8082/api/notebook',
  PANEL_API_BASE_URL: import.meta.env.VITE_PANEL_API_BASE_URL || 'http://localhost:8082/api/panels',
  FILE_API_BASE_URL: import.meta.env.VITE_FILE_API_BASE_URL || 'http://localhost:8085/api/files',
  CAPTCHA_API_BASE_URL: import.meta.env.VITE_CAPTCHA_API_BASE_URL || 'http://localhost:8089/api/captcha',
  FORUM_API_BASE_URL: import.meta.env.VITE_FORUM_API_BASE_URL || 'http://localhost:8086/api/forum',
  CHAT_API_BASE_URL: import.meta.env.VITE_CHAT_API_BASE_URL || 'http://localhost:8087/api/messages',
  MAIL_API_BASE_URL: import.meta.env.VITE_MAIL_API_BASE_URL || 'http://localhost:8087/api/mails',
  CATEGORY_API_BASE_URL: import.meta.env.VITE_CATEGORY_API_BASE_URL || 'http://localhost:8087/api/categories',
  CHAT_WS_BASE_URL: import.meta.env.VITE_CHAT_WS_BASE_URL || 'ws://localhost:8087/api/messages/ws/chat/',
  RESOURCE_API_BASE_URL: import.meta.env.VITE_RESOURCE_BASE_URL || 'http://localhost:8088/api/resources',
  ITEM_API_BASE_URL: import.meta.env.VITE_ITEM_BASE_URL || 'http://localhost:8088/api/items',
  MINING_API_BASE_URL: import.meta.env.VITE_MINING_API_BASE_URL || 'http://localhost:8088/api/admin',
  ECONOMY_API_BASE_URL: import.meta.env.VITE_ECONOMY_API_BASE_URL || 'http://localhost:8090/api/economy',
  CHARACTER_WS_BASE_URL: import.meta.env.VITE_CHARACTER_WS_BASE_URL || 'ws://localhost:8082/ws/character',  
  STATS_API_BASE_URL: import.meta.env.VITE_STATS_API_BASE_URL || 'http://localhost:8082/api/stats',
  REST_API_BASE_URL: import.meta.env.VITE_REST_API_BASE_URL || 'http://localhost:8082/api/rest',
  HOUSES_API_BASE_URL: import.meta.env.VITE_HOUSES_API_BASE_URL || 'http://localhost:8082/api/houses',
};
