// ============================================================
// locationTextConfig.js
// ============================================================
const DEFAULTS = {
  recipeColumn: 'Рецепт',
  buyTab: 'Купить Рецепты',
  yourTab: 'Ваши Рецепты',
  workshopTab: 'Рецепты',
  workshopNameColumn: 'Предмет',
  showRace: false,
  noRecipesText: 'Нет рецептов',
  recipeActionPrefix: 'Рецепт на изготовление',
  recipeUnit: 'партий',
  wearColumnLabel: 'Срок',
  capacityColumnLabel: 'Объём',
  shopTypeName: 'лавку',
  setPriceTitle: 'Установить цену',
  priceLabel: 'Цена (дт.):',
  cancelButton: 'Отмена',
  moveToShopButton: 'В лавку',
  sellButton: 'Продать',
  withdrawButton: 'Забрать',
  onSaleTitle: 'На продаже',
  shopItemsTitle: 'Товары на продажу',
  purchaseButton: 'Приобрести',
  craftingTab: 'Изготовление',
  emptyShopText: 'Нет предметов в лавке',
};

export const LOCATION_TEXT_CONFIG = {
  '1.9.pharmacy': {
    recipeColumn: 'Рецепт',
    buyTab: 'Купить Рецепты',
    yourTab: 'Ваши Рецепты',
    workshopTab: 'Рецепты Эликсиров',
    workshopNameColumn: 'Эликсир',
    showRace: true,
    recipeActionPrefix: 'Рецепт на изготовление',
    recipeUnit: 'партий',
    wearColumnLabel: 'Срок',
    shopTypeName: 'аптеку',
    shopTypeGenitive: 'аптеки',
    noRecipesText: 'Нет рецептов',
    emptyShopText: 'Нет предметов в аптеке',
  },
  '1.25.fish-shop': {
    recipeColumn: 'Рецепт',
    buyTab: 'Купить Рецепты',
    yourTab: 'Ваши Рецепты',
    workshopTab: 'Рецепты Блюд',
    workshopNameColumn: 'Блюдо',
    recipeActionPrefix: 'Рецепт на приготовление',
    recipeUnit: 'партий',
    wearColumnLabel: 'Срок',
    shopTypeName: 'лавку',
    shopTypeGenitive: 'лавки',
    noRecipesText: 'Нет рецептов',
    emptyShopText: 'Нет предметов в рыбной лавке',
  },
  '1.22.hunting-shop': {
    recipeColumn: 'Рецепт',
    buyTab: 'Купить Рецепты',
    yourTab: 'Ваши Рецепты',
    workshopTab: 'Рецепты Масел',
    workshopNameColumn: 'Масло',
    recipeActionPrefix: 'Рецепт на изготовление',
    recipeUnit: 'партий',
    wearColumnLabel: 'Срок',
    shopTypeName: 'лавку',
    shopTypeGenitive: 'лавки',
    noRecipesText: 'Нет рецептов',
    emptyShopText: 'Нет предметов в охотничьей лавке',
  },
  '1.21.furniture-shop': {
    recipeColumn: 'Чертеж',
    buyTab: 'Купить Чертежи',
    yourTab: 'Ваши Чертежи',
    workshopTab: 'Чертежи',
    workshopNameColumn: 'Мебель',
    recipeActionPrefix: 'Чертеж на изготовление',
    recipeUnit: 'предметов',
    wearColumnLabel: 'Износ',
    shopTypeName: 'лавку',
    shopTypeGenitive: 'лавки',
    noRecipesText: 'Нет чертежей',
    emptyShopText: 'Нет предметов в мебельной лавке',
  },
  '1.24.bird-market': {
    recipeColumn: 'Секрет',
    buyTab: 'Купить Секреты',
    yourTab: 'Ваши Секреты',
    workshopTab: 'Секреты',
    workshopNameColumn: 'Дракон',
    recipeActionPrefix: 'Секрет на выведение',
    recipeUnit: 'драконов',
    wearColumnLabel: 'Время жизни',
    shopTypeName: 'питомник',
    shopTypeGenitive: 'питомника',
    noRecipesText: 'Нет секретов',
    emptyShopText: 'Нет предметов в питомнике',
  },
  '1.13.forge': {
    recipeColumn: 'Секрет',
    buyTab: 'Купить Секреты',
    yourTab: 'Ваши Секреты',
    workshopTab: 'Секреты',
    workshopNameColumn: 'Изделие',
    recipeActionPrefix: 'Секрет на изготовление',
    recipeUnit: 'предметов',
    shopTypeName: 'кузницу',
    shopTypeGenitive: 'кузницы',
    noRecipesText: 'Нет секретов',
  },
  '1.16.jewelers': {
    recipeColumn: 'Секрет',
    buyTab: 'Купить Секреты',
    yourTab: 'Ваши Секреты',
    workshopTab: 'Секреты',
    workshopNameColumn: 'Украшение',
    recipeActionPrefix: 'Секрет на изготовление',
    recipeUnit: 'предметов',
    shopTypeName: 'ювелирную',
    shopTypeGenitive: 'ювелирной',
    noRecipesText: 'Нет секретов',
  },
  '1.27.trade-hall': {
    wearColumnLabel: 'Износ',
    workshopNameColumn: 'Вещь',
    shopTypeName: 'палатку',
    shopTypeGenitive: 'палатки',
    emptyShopText: 'Нет предметов в палатке',
  },
};

export const getLocationTexts = (locationSlug) => {
  return { ...DEFAULTS, ...(LOCATION_TEXT_CONFIG[locationSlug] || {}) };
};