"""clean_init

Revision ID: 48e07d94ed32
Revises: 
Create Date: 2026-10-05 00:00:51.496718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48e07d94ed32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE IF NOT EXISTS house_number_seq START WITH 1")
    op.create_table('character_attachment_settings',
    sa.Column('attach_cost', sa.Integer(), nullable=False),
    sa.Column('detach_cost', sa.Integer(), nullable=False),
    sa.Column('attach_cost_per_level', sa.Integer(), nullable=False),
    sa.Column('detach_cost_per_level', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('character_attachment_settings_pkey'))
    )
    op.create_table('cities',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cities_pkey'))
    )
    op.create_index(op.f('cities_name_idx'), 'cities', ['name'], unique=False)
    op.create_index(op.f('cities_serial_number_idx'), 'cities', ['serial_number'], unique=False)
    op.create_table('exchange_settings',
    sa.Column('min_ducats_on_slot', sa.Integer(), nullable=False),
    sa.Column('max_ducats_on_slot', sa.Integer(), nullable=False),
    sa.Column('min_gold_on_slot', sa.Integer(), nullable=False),
    sa.Column('max_gold_on_slot', sa.Integer(), nullable=False),
    sa.Column('min_course_on_gold', sa.Integer(), nullable=False),
    sa.Column('max_course_on_gold', sa.Integer(), nullable=False),
    sa.Column('seller_on_ducats_tax', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('exchange_settings_pkey'))
    )
    op.create_table('global_character_experience_settings',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('up', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('base', sa.Integer(), nullable=False),
    sa.Column('weapon_skill', sa.Integer(), nullable=False),
    sa.Column('race_parameter', sa.Integer(), nullable=False),
    sa.Column('skills', sa.Integer(), nullable=False),
    sa.Column('ducats', sa.Integer(), nullable=False),
    sa.Column('endurance', sa.Integer(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('global_character_experience_settings_pkey')),
    sa.UniqueConstraint('experience', name=op.f('global_character_experience_settings_experience_key'))
    )
    op.create_index(op.f('global_character_experience_settings_level_idx'), 'global_character_experience_settings', ['level'], unique=False)
    op.create_table('global_character_settings',
    sa.Column('default_experience', sa.Integer(), nullable=False),
    sa.Column('default_level', sa.Integer(), nullable=False),
    sa.Column('default_health', sa.Float(), nullable=False),
    sa.Column('default_max_health', sa.Float(), nullable=False),
    sa.Column('default_mana', sa.Float(), nullable=False),
    sa.Column('default_max_mana', sa.Float(), nullable=False),
    sa.Column('default_tiredness', sa.Float(), nullable=False),
    sa.Column('default_max_tiredness', sa.Float(), nullable=False),
    sa.Column('default_weight', sa.Integer(), nullable=False),
    sa.Column('default_max_weight', sa.Integer(), nullable=False),
    sa.Column('default_endurance', sa.Integer(), nullable=False),
    sa.Column('default_intelligence', sa.Integer(), nullable=False),
    sa.Column('default_gold', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('default_ducats', sa.Numeric(precision=18, scale=2), server_default='3', nullable=False),
    sa.Column('health_multiplier', sa.Float(), nullable=False),
    sa.Column('mana_multiplier', sa.Float(), nullable=False),
    sa.Column('max_characters_on_user', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('global_character_settings_pkey'))
    )
    op.create_table('inventory_item_work_accumulator',
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('work_minutes', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_item_work_accumulator_pkey'))
    )
    op.create_index(op.f('inventory_item_work_accumulator_inventory_item_id_idx'), 'inventory_item_work_accumulator', ['inventory_item_id'], unique=True)
    op.create_table('race_settings',
    sa.Column('race', sa.Enum('HUMAN', 'ELF', 'ORC', name='race'), nullable=False),
    sa.Column('base_power', sa.Integer(), nullable=False),
    sa.Column('base_agility', sa.Integer(), nullable=False),
    sa.Column('base_lucky', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('race_settings_pkey')),
    sa.UniqueConstraint('race', name=op.f('race_settings_race_key'))
    )
    op.create_table('referral_links',
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('referral_code', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('current_uses', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('referral_links_pkey'))
    )
    op.create_index(op.f('referral_links_referral_code_idx'), 'referral_links', ['referral_code'], unique=True)
    op.create_index(op.f('referral_links_referrer_id_idx'), 'referral_links', ['referrer_id'], unique=False)
    op.create_table('transfer_value_characters_settings',
    sa.Column('min_transfer_level', sa.Integer(), nullable=False),
    sa.Column('min_transfer_ducats', sa.Numeric(precision=18, scale=2), server_default='3', nullable=False),
    sa.Column('min_transfer_gold', sa.Numeric(precision=18, scale=2), server_default='0.01', nullable=False),
    sa.Column('transfer_tax_percentage', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('transfer_value_characters_settings_pkey'))
    )
    op.create_table('user_character_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('max_characters', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_character_settings_pkey'))
    )
    op.create_index(op.f('user_character_settings_user_id_idx'), 'user_character_settings', ['user_id'], unique=True)
    op.create_table('locations',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('RESOURCES', 'ITEMS', 'REST', 'OTHER', name='locationtype'), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], name=op.f('locations_city_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('locations_pkey'))
    )
    op.create_index(op.f('locations_city_id_idx'), 'locations', ['city_id'], unique=False)
    op.create_index(op.f('locations_name_idx'), 'locations', ['name'], unique=False)
    op.create_index(op.f('locations_serial_number_idx'), 'locations', ['serial_number'], unique=False)
    op.create_index(op.f('locations_slug_idx'), 'locations', ['slug'], unique=True)
    op.create_index(op.f('locations_type_idx'), 'locations', ['type'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('referred_user_id', sa.UUID(), nullable=False),
    sa.Column('referral_link_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referral_link_id'], ['referral_links.id'], name=op.f('referrals_referral_link_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('referrals_pkey'))
    )
    op.create_index(op.f('referrals_referral_link_id_idx'), 'referrals', ['referral_link_id'], unique=False)
    op.create_index(op.f('referrals_referred_user_id_idx'), 'referrals', ['referred_user_id'], unique=False)
    op.create_index(op.f('referrals_referrer_id_idx'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('characters',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('location_slug', sa.String(length=128), nullable=True),
    sa.Column('is_male', sa.Boolean(), nullable=False),
    sa.Column('race', sa.Enum('HUMAN', 'ELF', 'ORC', name='race'), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('health', sa.Float(), nullable=False),
    sa.Column('max_health', sa.Float(), nullable=False),
    sa.Column('tiredness', sa.Float(), nullable=False),
    sa.Column('max_tiredness', sa.Float(), nullable=False),
    sa.Column('endurance', sa.Integer(), nullable=False),
    sa.Column('mana', sa.Float(), nullable=False),
    sa.Column('max_mana', sa.Float(), nullable=False),
    sa.Column('intelligence', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('max_weight', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Numeric(precision=18, scale=2), server_default='0', nullable=False),
    sa.Column('ducats', sa.Numeric(precision=18, scale=2), server_default='3', nullable=False),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('agility', sa.Integer(), nullable=False),
    sa.Column('lucky', sa.Integer(), nullable=False),
    sa.Column('equipment_bonuses', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('mastership_sword', sa.Integer(), nullable=False),
    sa.Column('mastership_axe', sa.Integer(), nullable=False),
    sa.Column('mastership_hammer', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_deletion_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('food_cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rest_state', sa.String(length=32), nullable=True),
    sa.Column('current_house_id', sa.UUID(), nullable=True),
    sa.Column('current_room_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_slug'], ['locations.slug'], name=op.f('characters_location_slug_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('characters_pkey'))
    )
    op.create_index(op.f('characters_current_house_id_idx'), 'characters', ['current_house_id'], unique=False)
    op.create_index(op.f('characters_current_room_id_idx'), 'characters', ['current_room_id'], unique=False)
    op.create_index(op.f('characters_location_slug_idx'), 'characters', ['location_slug'], unique=False)
    op.create_index(op.f('characters_name_idx'), 'characters', ['name'], unique=True)
    op.create_index(op.f('characters_photo_id_idx'), 'characters', ['photo_id'], unique=False)
    op.create_index(op.f('characters_rest_state_idx'), 'characters', ['rest_state'], unique=False)
    op.create_index(op.f('characters_scheduled_deletion_at_idx'), 'characters', ['scheduled_deletion_at'], unique=False)
    op.create_index(op.f('characters_user_id_idx'), 'characters', ['user_id'], unique=False)
    op.create_table('applied_character_history',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('count_applied_power', sa.Integer(), nullable=False),
    sa.Column('count_applied_agility', sa.Integer(), nullable=False),
    sa.Column('count_applied_lucky', sa.Integer(), nullable=False),
    sa.Column('count_applied_endurance', sa.Integer(), nullable=False),
    sa.Column('count_applied_intelligence', sa.Integer(), nullable=False),
    sa.Column('count_applied_mastership_sword', sa.Integer(), nullable=False),
    sa.Column('count_applied_mastership_axe', sa.Integer(), nullable=False),
    sa.Column('count_applied_mastership_hammer', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('applied_character_history_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('applied_character_history_pkey'))
    )
    op.create_index(op.f('applied_character_history_character_id_idx'), 'applied_character_history', ['character_id'], unique=True)
    op.create_table('character_ability_settings',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('count_stats', sa.Integer(), nullable=False),
    sa.Column('count_mastership', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('character_ability_settings_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('character_ability_settings_pkey'))
    )
    op.create_index(op.f('character_ability_settings_character_id_idx'), 'character_ability_settings', ['character_id'], unique=True)
    op.create_table('character_buffs',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('buff_type', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stack_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('character_buffs_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('character_buffs_pkey'))
    )
    op.create_index(op.f('character_buffs_buff_type_idx'), 'character_buffs', ['buff_type'], unique=False)
    op.create_index(op.f('character_buffs_character_id_idx'), 'character_buffs', ['character_id'], unique=False)
    op.create_table('character_currency_operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('operation_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('operation_type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('counterparty_id', sa.UUID(), nullable=True),
    sa.Column('item_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('character_currency_operations_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('character_currency_operations_pkey'))
    )
    op.create_index(op.f('character_currency_operations_character_id_idx'), 'character_currency_operations', ['character_id'], unique=False)
    op.create_index(op.f('character_currency_operations_counterparty_id_idx'), 'character_currency_operations', ['counterparty_id'], unique=False)
    op.create_index(op.f('character_currency_operations_currency_idx'), 'character_currency_operations', ['currency'], unique=False)
    op.create_index(op.f('character_currency_operations_operation_id_idx'), 'character_currency_operations', ['operation_id'], unique=True)
    op.create_index(op.f('character_currency_operations_source_idx'), 'character_currency_operations', ['source'], unique=False)
    op.create_table('character_distributions',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('count_distributions', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('skill_type', sa.Enum('STANDARD', 'MASTERSHIP', name='characterskilltype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('character_distributions_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('character_distributions_pkey')),
    sa.UniqueConstraint('character_id', 'skill_type', name='uq_character_skill_type')
    )
    op.create_index(op.f('character_distributions_character_id_idx'), 'character_distributions', ['character_id'], unique=False)
    op.create_index(op.f('character_distributions_skill_type_idx'), 'character_distributions', ['skill_type'], unique=False)
    op.create_table('character_trade_privileges',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('gold_trade_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_admin_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('character_trade_privileges_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('character_trade_privileges_pkey'))
    )
    op.create_index(op.f('character_trade_privileges_character_id_idx'), 'character_trade_privileges', ['character_id'], unique=True)
    op.create_table('characters_activity',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.Enum('PLAY', 'QUIT', 'LOGOUT', 'BUTTON_CLICK', 'ITEM_USE', 'QUEST_START', 'QUEST_COMPLETE', name='actiontype'), nullable=False),
    sa.Column('action_details', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('characters_activity_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('characters_activity_pkey'))
    )
    op.create_table('characters_fast_items',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('first_item', sa.Enum('MAP', 'INVENTORY', 'PARAMETERS', 'MAGIC', 'FRIENDS', 'SETTINGS', 'CAMPAIGN', 'EARN', 'NOTEBOOK', 'CABINET', name='menuitem'), nullable=True),
    sa.Column('second_item', sa.Enum('MAP', 'INVENTORY', 'PARAMETERS', 'MAGIC', 'FRIENDS', 'SETTINGS', 'CAMPAIGN', 'EARN', 'NOTEBOOK', 'CABINET', name='menuitem'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('characters_fast_items_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('characters_fast_items_pkey'))
    )
    op.create_index(op.f('characters_fast_items_character_id_idx'), 'characters_fast_items', ['character_id'], unique=True)
    op.create_table('characters_info',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('country', sa.String(length=25), nullable=True),
    sa.Column('city', sa.String(length=25), nullable=True),
    sa.Column('info', sa.String(length=5000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('characters_info_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('characters_info_pkey'))
    )
    op.create_index(op.f('characters_info_character_id_idx'), 'characters_info', ['character_id'], unique=True)
    op.create_table('houses',
    sa.Column('owner_character_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('location_slug', sa.String(length=128), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_volume', sa.Integer(), server_default='0', nullable=False),
    sa.Column('regen_multipliers', postgresql.JSONB(astext_type=sa.Text()), server_default='{"health": 1.0, "mana": 1.0, "tiredness": 1.0}', nullable=False),
    sa.Column('wallpaper_photo_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_character_id'], ['characters.id'], name=op.f('houses_owner_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('houses_pkey'))
    )
    op.create_index(op.f('houses_location_slug_idx'), 'houses', ['location_slug'], unique=False)
    op.create_index(op.f('houses_number_idx'), 'houses', ['number'], unique=True)
    op.create_index(op.f('houses_owner_character_id_idx'), 'houses', ['owner_character_id'], unique=False)
    op.create_table('notebooks',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=5000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('notebooks_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notebooks_pkey'))
    )
    op.create_index(op.f('notebooks_character_id_idx'), 'notebooks', ['character_id'], unique=True)
    op.create_table('rest_rental_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('rented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('rest_rental_history_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rest_rental_history_pkey'))
    )
    op.create_index(op.f('rest_rental_history_character_id_idx'), 'rest_rental_history', ['character_id'], unique=False)
    op.create_table('rest_rentals',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('rented_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('rest_rentals_character_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rest_rentals_pkey'))
    )
    op.create_index(op.f('rest_rentals_character_id_idx'), 'rest_rentals', ['character_id'], unique=True)
    op.create_index(op.f('rest_rentals_expires_at_idx'), 'rest_rentals', ['expires_at'], unique=False)
    op.create_table('slots',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('ducats', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('gold', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('buy_for', sa.Enum('DUCATS', 'GOLD', name='currency'), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['characters.id'], name=op.f('slots_seller_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('slots_pkey')),
    sa.UniqueConstraint('number', name=op.f('slots_number_key'))
    )
    op.create_table('house_furniture',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('house_furniture_house_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('house_furniture_pkey'))
    )
    op.create_index(op.f('house_furniture_house_id_idx'), 'house_furniture', ['house_id'], unique=False)
    op.create_index(op.f('house_furniture_inventory_item_id_idx'), 'house_furniture', ['inventory_item_id'], unique=True)
    op.create_table('house_guest_requests',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('house_guest_requests_character_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('house_guest_requests_house_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('house_guest_requests_pkey')),
    sa.UniqueConstraint('house_id', 'character_id', name='uq_house_guest_requests_house_character')
    )
    op.create_index(op.f('house_guest_requests_character_id_idx'), 'house_guest_requests', ['character_id'], unique=False)
    op.create_index(op.f('house_guest_requests_expires_at_idx'), 'house_guest_requests', ['expires_at'], unique=False)
    op.create_index(op.f('house_guest_requests_house_id_idx'), 'house_guest_requests', ['house_id'], unique=False)
    op.create_table('house_guests',
    sa.Column('house_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('house_guests_character_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name=op.f('house_guests_house_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('house_guests_pkey'))
    )
    op.create_index(op.f('house_guests_character_id_idx'), 'house_guests', ['character_id'], unique=True)
    op.create_index(op.f('house_guests_house_id_idx'), 'house_guests', ['house_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SEQUENCE IF EXISTS house_number_seq")
    op.drop_index(op.f('house_guests_house_id_idx'), table_name='house_guests')
    op.drop_index(op.f('house_guests_character_id_idx'), table_name='house_guests')
    op.drop_table('house_guests')
    op.drop_index(op.f('house_guest_requests_house_id_idx'), table_name='house_guest_requests')
    op.drop_index(op.f('house_guest_requests_expires_at_idx'), table_name='house_guest_requests')
    op.drop_index(op.f('house_guest_requests_character_id_idx'), table_name='house_guest_requests')
    op.drop_table('house_guest_requests')
    op.drop_index(op.f('house_furniture_inventory_item_id_idx'), table_name='house_furniture')
    op.drop_index(op.f('house_furniture_house_id_idx'), table_name='house_furniture')
    op.drop_table('house_furniture')
    op.drop_table('slots')
    op.drop_index(op.f('rest_rentals_expires_at_idx'), table_name='rest_rentals')
    op.drop_index(op.f('rest_rentals_character_id_idx'), table_name='rest_rentals')
    op.drop_table('rest_rentals')
    op.drop_index(op.f('rest_rental_history_character_id_idx'), table_name='rest_rental_history')
    op.drop_table('rest_rental_history')
    op.drop_index(op.f('notebooks_character_id_idx'), table_name='notebooks')
    op.drop_table('notebooks')
    op.drop_index(op.f('houses_owner_character_id_idx'), table_name='houses')
    op.drop_index(op.f('houses_number_idx'), table_name='houses')
    op.drop_index(op.f('houses_location_slug_idx'), table_name='houses')
    op.drop_table('houses')
    op.drop_index(op.f('characters_info_character_id_idx'), table_name='characters_info')
    op.drop_table('characters_info')
    op.drop_index(op.f('characters_fast_items_character_id_idx'), table_name='characters_fast_items')
    op.drop_table('characters_fast_items')
    op.drop_table('characters_activity')
    op.drop_index(op.f('character_trade_privileges_character_id_idx'), table_name='character_trade_privileges')
    op.drop_table('character_trade_privileges')
    op.drop_index(op.f('character_distributions_skill_type_idx'), table_name='character_distributions')
    op.drop_index(op.f('character_distributions_character_id_idx'), table_name='character_distributions')
    op.drop_table('character_distributions')
    op.drop_index(op.f('character_currency_operations_source_idx'), table_name='character_currency_operations')
    op.drop_index(op.f('character_currency_operations_operation_id_idx'), table_name='character_currency_operations')
    op.drop_index(op.f('character_currency_operations_currency_idx'), table_name='character_currency_operations')
    op.drop_index(op.f('character_currency_operations_counterparty_id_idx'), table_name='character_currency_operations')
    op.drop_index(op.f('character_currency_operations_character_id_idx'), table_name='character_currency_operations')
    op.drop_table('character_currency_operations')
    op.drop_index(op.f('character_buffs_character_id_idx'), table_name='character_buffs')
    op.drop_index(op.f('character_buffs_buff_type_idx'), table_name='character_buffs')
    op.drop_table('character_buffs')
    op.drop_index(op.f('character_ability_settings_character_id_idx'), table_name='character_ability_settings')
    op.drop_table('character_ability_settings')
    op.drop_index(op.f('applied_character_history_character_id_idx'), table_name='applied_character_history')
    op.drop_table('applied_character_history')
    op.drop_index(op.f('characters_user_id_idx'), table_name='characters')
    op.drop_index(op.f('characters_scheduled_deletion_at_idx'), table_name='characters')
    op.drop_index(op.f('characters_rest_state_idx'), table_name='characters')
    op.drop_index(op.f('characters_photo_id_idx'), table_name='characters')
    op.drop_index(op.f('characters_name_idx'), table_name='characters')
    op.drop_index(op.f('characters_location_slug_idx'), table_name='characters')
    op.drop_index(op.f('characters_current_room_id_idx'), table_name='characters')
    op.drop_index(op.f('characters_current_house_id_idx'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('referrals_referrer_id_idx'), table_name='referrals')
    op.drop_index(op.f('referrals_referred_user_id_idx'), table_name='referrals')
    op.drop_index(op.f('referrals_referral_link_id_idx'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('locations_type_idx'), table_name='locations')
    op.drop_index(op.f('locations_slug_idx'), table_name='locations')
    op.drop_index(op.f('locations_serial_number_idx'), table_name='locations')
    op.drop_index(op.f('locations_name_idx'), table_name='locations')
    op.drop_index(op.f('locations_city_id_idx'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('user_character_settings_user_id_idx'), table_name='user_character_settings')
    op.drop_table('user_character_settings')
    op.drop_table('transfer_value_characters_settings')
    op.drop_index(op.f('referral_links_referrer_id_idx'), table_name='referral_links')
    op.drop_index(op.f('referral_links_referral_code_idx'), table_name='referral_links')
    op.drop_table('referral_links')
    op.drop_table('race_settings')
    op.drop_index(op.f('inventory_item_work_accumulator_inventory_item_id_idx'), table_name='inventory_item_work_accumulator')
    op.drop_table('inventory_item_work_accumulator')
    op.drop_table('global_character_settings')
    op.drop_index(op.f('global_character_experience_settings_level_idx'), table_name='global_character_experience_settings')
    op.drop_table('global_character_experience_settings')
    op.drop_table('exchange_settings')
    op.drop_index(op.f('cities_serial_number_idx'), table_name='cities')
    op.drop_index(op.f('cities_name_idx'), table_name='cities')
    op.drop_table('cities')
    op.drop_table('character_attachment_settings')
    # ### end Alembic commands ###
