// ============================================================
// recipeOrderConfig.js
// ============================================================
export const ITEM_TYPE_ORDER = {
  '1.13.forge': [
    'shield',
    'weapon',
    'cloak',
    'helmet',
    'armor',
    'gauntlets',
    'gloves',
    'leggings',
    'boots',
  ],
  '1.16.jewelers': [
    'amulet',
    'pendant',
    'ring',
  ],
};

export const RECIPE_ORDER_CONFIG = {
  '1.21.furniture-shop': [
    'i.fur.21.3.dining-table',
    'i.fur.21.3.single-bed',
    'i.fur.21.3.armchair',
    'i.fur.21.3.chair',
    'i.fur.21.3.small-bench',
    'i.fur.21.3.mirror',
    'i.fur.21.3.carpet',
    'i.fur.21.3.lamp',
  ],
  '1.9.pharmacy': [
    'i.el.9.3.elixir-fierce-warrior',
    'i.el.9.3.elixir-pursuit',
    'i.el.9.3.moment-truth',
    'i.el.9.3.white-day',
    'i.el.9.3.elixir-energy',
    'i.el.9.3.elixir-unclean-force',
    'i.el.9.3.elixir-bee-sting',
    'i.el.9.3.elixir-bear-song',
    'i.el.9.3.elixir-soberness',
    'i.el.9.3.elixir-full-moon',
    'i.el.9.3.elixir-cry-fools',
    'i.el.9.3.elixir-living-water',
    'i.el.9.3.elixir-pink-light',
    'i.el.9.3.elixir-light-way',
    'i.el.9.3.elixir-second-breath',
    'i.el.9.3.elixir-dispersion',
  ],
  '1.25.fish-shop': [
    'i.f.25.3.dried-goby',
    'i.f.25.3.dried-roach',
    'i.f.25.3.dried-crucian',
    'i.f.25.3.fried-carp',
    'i.f.25.3.fried-pike',
    'i.f.25.3.fried-catfish',
    'i.f.25.3.smoked-sturgeon',
  ],
  '1.22.hunting-shop': [
    'i.o.22.3.oil-against-swamp',
    'i.o.22.3.oil-against-mine',
    'i.o.22.3.oil-against-lake',
    'i.o.22.3.oil-against-sands',
    'i.o.22.3.oil-against-quarry',
    'i.o.22.3.oil-against-forest',
    'i.o.22.3.treasure-oil',
    'i.o.22.3.tales-oil',
  ],
  '1.24.bird-market': [
    'i.an.24.1.giant-dragon',
    'i.an.24.1.mountain-dragon',
    'i.an.24.1.ghost-dragon',
    'i.an.24.1.river-dragon',
    'i.an.24.1.battle-dragon',
    'i.an.24.1.fire-dragon',
  ],
  '1.13.forge': [
    // ЩИТЫ
    'i.shield.13.1.wooden-shield',
    'i.shield.13.2.forest-shield',
    'i.shield.13.3.shine-shield',
    'i.shield.13.3.rebuke-shield',
    'i.shield.13.3.attachment-shield',
    'i.shield.13.5.elf-pride-shield',
    'i.shield.13.5.contrast-shield',
    'i.shield.13.5.three-dozens-shield',
    'i.shield.13.7.giant-shield',
    'i.shield.13.7.great-defense-shield',
    'i.shield.13.7.indestructibility-shield',
    'i.shield.13.7.retaliation-shield',
    'i.shield.13.7.reconciliation-shield',
    'i.shield.13.7.fortitude-shield',
    'i.shield.13.7.refutation-shield',
    'i.shield.13.7.obstruction-shield',
    'i.shield.13.9.condescension-shield',
    'i.shield.13.9.experience-shield',
    'i.shield.13.9.judiciousness-shield',
    'i.shield.13.9.submission-shield',
    'i.shield.13.11.ancient-forest-shield',
    'i.shield.13.11.shadow-shield',
    'i.shield.13.11.eternal-twilight-shield',
    'i.shield.13.11.father-of-mountains-shield',
    'i.shield.13.11.primordial-fury-shield',
    // ОРУЖИЕ - МЕЧИ
    'i.weapon.13.1.hunting-knife',
    'i.weapon.13.1.general-dagger',
    'i.weapon.13.2.heavy-patterned-sword',
    'i.weapon.13.2.instruction-sword',
    'i.weapon.13.2.light-elven-sword',
    'i.weapon.13.4.constancy-sword',
    'i.weapon.13.4.confidence-sword',
    'i.weapon.13.4.strike-sword',
    'i.weapon.13.6.wind-sword',
    'i.weapon.13.6.valor-sword',
    'i.weapon.13.6.death-blade-sword',
    'i.weapon.13.8.exclusion-sword',
    'i.weapon.13.8.father-of-mountains-sword',
    'i.weapon.13.10.eternal-sleep-sword',
    'i.weapon.13.10.awakening-sword',
    'i.weapon.13.10.sharpness-of-mind-sword',
    'i.weapon.13.12.twilight-abbot-sword',
    'i.weapon.13.12.death-whisper-sword',
    'i.weapon.13.12.griffon-claw-sword',
    'i.weapon.13.12.heavenly-paladins-sword',
    // ОРУЖИЕ - ТОПОРЫ
    'i.weapon.13.1.axe-guard',
    'i.weapon.13.2.axe-moon',
    'i.weapon.13.2.axe-steel',
    'i.weapon.13.2.axe-forest',
    'i.weapon.13.4.axe-blood',
    'i.weapon.13.4.axe-lightness',
    'i.weapon.13.4.axe-cutter',
    'i.weapon.13.6.axe-punisher',
    'i.weapon.13.6.axe-order-guardian',
    'i.weapon.13.6.axe-vulture',
    'i.weapon.13.8.axe-heat',
    'i.weapon.13.8.axe-cold',
    'i.weapon.13.10.axe-good-messenger',
    'i.weapon.13.10.axe-divider',
    'i.weapon.13.10.axe-throat-biter',
    'i.weapon.13.10.axe-edge-of-madness',
    'i.weapon.13.12.axe-dragon-tamer',
    'i.weapon.13.12.axe-blood-shaman',
    'i.weapon.13.12.axe-dead-land',
    'i.weapon.13.12.axe-priest-antapeht',
    // ОРУЖИЕ - МОЛОТЫ
    'i.weapon.13.1.hammer-bandit-club',
    'i.weapon.13.2.hammer-flail-crusher',
    'i.weapon.13.2.hammer-warrior-mace',
    'i.weapon.13.2.hammer-druid-flail',
    'i.weapon.13.4.hammer-seeker',
    'i.weapon.13.4.hammer-peacemaker',
    'i.weapon.13.4.hammer-killer',
    'i.weapon.13.6.hammer-destroyer',
    'i.weapon.13.6.hammer-conqueror',
    'i.weapon.13.8.hammer-light-forces',
    'i.weapon.13.8.hammer-dark-forces',
    'i.weapon.13.10.hammer-switch-off',
    'i.weapon.13.10.hammer-heavy-hand',
    'i.weapon.13.10.hammer-sudden-kiss',
    'i.weapon.13.12.hammer-skull-grinder',
    'i.weapon.13.12.hammer-primal-fear',
    'i.weapon.13.12.hammer-swarud-hand',
    // ПЛАЩИ
    'i.cloak.13.6.harmony-balance-cloak',
    'i.cloak.13.6.harmony-order-cloak',
    'i.cloak.13.6.harmony-mind-cloak',
    'i.cloak.13.6.harmony-chaos-cloak',
    'i.cloak.13.6.harmony-feelings-cloak',
    'i.cloak.13.6.harmony-nature-cloak',
    'i.cloak.13.8.wisdom-balance-cloak',
    'i.cloak.13.8.wisdom-order-cloak',
    'i.cloak.13.8.wisdom-mind-cloak',
    'i.cloak.13.8.wisdom-chaos-cloak',
    'i.cloak.13.8.wisdom-feelings-cloak',
    'i.cloak.13.8.wisdom-nature-cloak',
    'i.cloak.13.10.power-balance-cloak',
    'i.cloak.13.10.power-order-cloak',
    'i.cloak.13.10.power-mind-cloak',
    'i.cloak.13.10.power-chaos-cloak',
    'i.cloak.13.10.power-feelings-cloak',
    'i.cloak.13.10.power-nature-cloak',
    'i.cloak.13.12.eternity-balance-cloak',
    'i.cloak.13.12.eternity-order-cloak',
    'i.cloak.13.12.eternity-mind-cloak',
    'i.cloak.13.12.eternity-chaos-cloak',
    'i.cloak.13.12.eternity-feelings-cloak',
    'i.cloak.13.12.eternity-nature-cloak',
    // БРОНЯ - БРОНЗОВЫЙ ОРК
    'i.helmet.13.4.orc-bronze-helmet',
    'i.armor.13.4.orc-bronze-armor',
    'i.gauntlets.13.4.orc-bronze-gauntlets',
    'i.gloves.13.4.orc-bronze-gloves',
    'i.leggings.13.4.orc-bronze-leggings',
    'i.boots.13.4.orc-bronze-boots',
    'i.armor.13.4.orc-bronze-kit',
    // БРОНЯ - БРОНЗОВЫЙ ЭЛЬФ
    'i.helmet.13.4.elf-bronze-helmet',
    'i.armor.13.4.elf-bronze-armor',
    'i.gauntlets.13.4.elf-bronze-gauntlets',
    'i.gloves.13.4.elf-bronze-gloves',
    'i.leggings.13.4.elf-bronze-leggings',
    'i.boots.13.4.elf-bronze-boots',
    'i.armor.13.4.elf-bronze-kit',
    // БРОНЯ - БРОНЗОВЫЙ ЧЕЛОВЕК
    'i.helmet.13.4.human-bronze-helmet',
    'i.armor.13.4.human-bronze-armor',
    'i.gauntlets.13.4.human-bronze-gauntlets',
    'i.gloves.13.4.human-bronze-gloves',
    'i.leggings.13.4.human-bronze-leggings',
    'i.boots.13.4.human-bronze-boots',
    'i.armor.13.4.human-bronze-kit',
    // БРОНЯ - СЕРЕБРЯНЫЙ ОРК
    'i.helmet.13.6.orc-silver-helmet',
    'i.armor.13.6.orc-silver-armor',
    'i.gauntlets.13.6.orc-silver-gauntlets',
    'i.gloves.13.6.orc-silver-gloves',
    'i.leggings.13.6.orc-silver-leggings',
    'i.boots.13.6.orc-silver-boots',
    'i.armor.13.6.orc-silver-kit',
    // БРОНЯ - СЕРЕБРЯНЫЙ ЭЛЬФ
    'i.helmet.13.6.elf-silver-helmet',
    'i.armor.13.6.elf-silver-armor',
    'i.gauntlets.13.6.elf-silver-gauntlets',
    'i.gloves.13.6.elf-silver-gloves',
    'i.leggings.13.6.elf-silver-leggings',
    'i.boots.13.6.elf-silver-boots',
    'i.armor.13.6.elf-silver-kit',
    // БРОНЯ - СЕРЕБРЯНЫЙ ЧЕЛОВЕК
    'i.helmet.13.6.human-silver-helmet',
    'i.armor.13.6.human-silver-armor',
    'i.gauntlets.13.6.human-silver-gauntlets',
    'i.gloves.13.6.human-silver-gloves',
    'i.leggings.13.6.human-silver-leggings',
    'i.boots.13.6.human-silver-boots',
    'i.armor.13.6.human-silver-kit',
    // БРОНЯ - ЗОЛОТОЙ ОРК
    'i.helmet.13.8.orc-golden-helmet',
    'i.armor.13.8.orc-golden-armor',
    'i.gauntlets.13.8.orc-golden-gauntlets',
    'i.gloves.13.8.orc-golden-gloves',
    'i.leggings.13.8.orc-golden-leggings',
    'i.boots.13.8.orc-golden-boots',
    'i.armor.13.8.orc-golden-kit',
    // БРОНЯ - ЗОЛОТОЙ ЭЛЬФ
    'i.helmet.13.8.elf-golden-helmet',
    'i.armor.13.8.elf-golden-armor',
    'i.gauntlets.13.8.elf-golden-gauntlets',
    'i.gloves.13.8.elf-golden-gloves',
    'i.leggings.13.8.elf-golden-leggings',
    'i.boots.13.8.elf-golden-boots',
    'i.armor.13.8.elf-golden-kit',
    // БРОНЯ - ЗОЛОТОЙ ЧЕЛОВЕК
    'i.helmet.13.8.human-golden-helmet',
    'i.armor.13.8.human-golden-armor',
    'i.gauntlets.13.8.human-golden-gauntlets',
    'i.gloves.13.8.human-golden-gloves',
    'i.leggings.13.8.human-golden-leggings',
    'i.boots.13.8.human-golden-boots',
    'i.armor.13.8.human-golden-kit',
    // БРОНЯ - МИФРИЛОВЫЙ ОРК
    'i.helmet.13.10.orc-mithril-helmet',
    'i.armor.13.10.orc-mithril-armor',
    'i.gauntlets.13.10.orc-mithril-gauntlets',
    'i.gloves.13.10.orc-mithril-gloves',
    'i.leggings.13.10.orc-mithril-leggings',
    'i.boots.13.10.orc-mithril-boots',
    'i.armor.13.10.orc-mithril-kit',
    // БРОНЯ - МИФРИЛОВЫЙ ЭЛЬФ
    'i.helmet.13.10.elf-mithril-helmet',
    'i.armor.13.10.elf-mithril-armor',
    'i.gauntlets.13.10.elf-mithril-gauntlets',
    'i.gloves.13.10.elf-mithril-gloves',
    'i.leggings.13.10.elf-mithril-leggings',
    'i.boots.13.10.elf-mithril-boots',
    'i.armor.13.10.elf-mithril-kit',
    // БРОНЯ - МИФРИЛОВЫЙ ЧЕЛОВЕК
    'i.helmet.13.10.human-mithril-helmet',
    'i.armor.13.10.human-mithril-armor',
    'i.gauntlets.13.10.human-mithril-gauntlets',
    'i.gloves.13.10.human-mithril-gloves',
    'i.leggings.13.10.human-mithril-leggings',
    'i.boots.13.10.human-mithril-boots',
    'i.armor.13.10.human-mithril-kit',
    // БРОНЯ - ТЁМНЫЙ ОРК
    'i.helmet.13.12.orc-dark-helmet',
    'i.armor.13.12.orc-dark-armor',
    'i.gauntlets.13.12.orc-dark-gauntlets',
    'i.gloves.13.12.orc-dark-gloves',
    'i.leggings.13.12.orc-dark-leggings',
    'i.boots.13.12.orc-dark-boots',
    'i.armor.13.12.orc-dark-kit',
    // БРОНЯ - ТЁМНЫЙ ЭЛЬФ
    'i.helmet.13.12.elf-dark-helmet',
    'i.armor.13.12.elf-dark-armor',
    'i.gauntlets.13.12.elf-dark-gauntlets',
    'i.gloves.13.12.elf-dark-gloves',
    'i.leggings.13.12.elf-dark-leggings',
    'i.boots.13.12.elf-dark-boots',
    'i.armor.13.12.elf-dark-kit',
    // БРОНЯ - ТЁМНЫЙ ЧЕЛОВЕК
    'i.helmet.13.12.human-dark-helmet',
    'i.armor.13.12.human-dark-armor',
    'i.gauntlets.13.12.human-dark-gauntlets',
    'i.gloves.13.12.human-dark-gloves',
    'i.leggings.13.12.human-dark-leggings',
    'i.boots.13.12.human-dark-boots',
    'i.armor.13.12.human-dark-kit',
  ],
  '1.16.jewelers': [
    // АМУЛЕТЫ
    'i.amulet.16.3.luck-amulet',
    'i.amulet.16.3.jump-amulet',
    'i.amulet.16.3.tree-strength-amulet',
    'i.amulet.16.4.wind-amulet',
    'i.amulet.16.4.acrobat-amulet',
    'i.amulet.16.4.rough-luck-amulet',
    'i.amulet.16.5.beast-attack-amulet',
    'i.amulet.16.5.lucky-attack-amulet',
    'i.amulet.16.5.stable-attack-amulet',
    'i.amulet.16.5.art-amulet',
    'i.amulet.16.5.precision-strike-amulet',
    'i.amulet.16.5.mountain-dwarves-amulet',
    'i.amulet.16.6.giant-amulet',
    'i.amulet.16.6.target-vision-amulet',
    'i.amulet.16.6.equilibrium-amulet',
    'i.amulet.16.7.destruction-amulet',
    'i.amulet.16.7.freedom-amulet',
    'i.amulet.16.7.wolf-amulet',
    'i.amulet.16.8.levitation-amulet',
    'i.amulet.16.8.father-of-mountains-amulet',
    'i.amulet.16.8.heir-amulet',
    'i.amulet.16.9.crusader-amulet',
    'i.amulet.16.9.shadow-secrets-amulet',
    'i.amulet.16.9.viking-amulet',
    'i.amulet.16.9.centaur-amulet',
    'i.amulet.16.9.zeus-breath-amulet',
    'i.amulet.16.10.ruby-heart-amulet',
    'i.amulet.16.10.beholder-eye-amulet',
    'i.amulet.16.10.euphoria-amulet',
    'i.amulet.16.10.barbarian-amulet',
    'i.amulet.16.11.vengeance-amulet',
    'i.amulet.16.11.salamander-amulet',
    'i.amulet.16.11.sorrow-amulet',
    'i.amulet.16.11.fatal-mistake-amulet',
    'i.amulet.16.12.piercing-strike-amulet',
    'i.amulet.16.12.deception-amulet',
    'i.amulet.16.12.balance-amulet',
    'i.amulet.16.12.immortality-amulet',
    'i.amulet.16.12.hunter-amulet',
    // КУЛОНЫ
    'i.pendant.16.3.beast-defense',
    'i.pendant.16.3.valor',
    'i.pendant.16.3.hardness',
    'i.pendant.16.4.strong-spirit',
    'i.pendant.16.4.perseverance',
    'i.pendant.16.4.healthy-spirit',
    'i.pendant.16.4.straightness',
    'i.pendant.16.5.forest-protection',
    'i.pendant.16.5.ferocious-beast',
    'i.pendant.16.5.feat',
    'i.pendant.16.6.attentiveness',
    'i.pendant.16.6.king-of-beasts',
    'i.pendant.16.6.hero',
    'i.pendant.16.6.thug',
    'i.pendant.16.6.endurance',
    'i.pendant.16.7.tears',
    'i.pendant.16.7.rigidity',
    'i.pendant.16.7.lightness',
    'i.pendant.16.8.father-of-mountains',
    'i.pendant.16.8.resistance',
    'i.pendant.16.8.circular-defense',
    'i.pendant.16.9.blinding-lightning',
    'i.pendant.16.9.universe-power',
    'i.pendant.16.9.blood-of-gods',
    'i.pendant.16.10.drop-of-blood',
    'i.pendant.16.10.golem-heart',
    'i.pendant.16.10.lightning-angel',
    'i.pendant.16.11.preacher',
    'i.pendant.16.11.seal-of-chaos',
    'i.pendant.16.11.evolution',
    'i.pendant.16.12.insight',
    'i.pendant.16.12.retribution',
    'i.pendant.16.12.tranquility',
    'i.pendant.16.12.eternity',
    // КОЛЬЦА
    'i.ring.16.2.unbreakable-attack',
    'i.ring.16.2.bloody-attack',
    'i.ring.16.2.fast-attack',
    'i.ring.16.3.luck-ring',
    'i.ring.16.3.strike-ring',
    'i.ring.16.3.reaction-ring',
    'i.ring.16.3.berserker-ring',
    'i.ring.16.3.confrontation-ring',
    'i.ring.16.4.true-health-ring',
    'i.ring.16.4.glorious-health-ring',
    'i.ring.16.4.ephemeral-health-ring',
    'i.ring.16.5.immunity-ring',
    'i.ring.16.5.glory-ring',
    'i.ring.16.5.wood-gods-ring',
    'i.ring.16.5.stone-spirit-ring',
    'i.ring.16.5.fast-death-ring',
    'i.ring.16.5.air-energy-ring',
    'i.ring.16.7.elemental-ring',
    'i.ring.16.7.impregnability-ring',
    'i.ring.16.7.oblivion-ring',
    'i.ring.16.7.fidelity-ring',
    'i.ring.16.7.treachery-ring',
    'i.ring.16.7.infinity-ring',
    'i.ring.16.9.peacemaker-ring',
    'i.ring.16.9.might-ring',
    'i.ring.16.9.unyielding-wind-ring',
    'i.ring.16.9.darkness-absorption-ring',
    'i.ring.16.9.fading-light-ring',
    'i.ring.16.9.confidence-ring',
    'i.ring.16.11.suppression-ring',
    'i.ring.16.11.scorpion-ring',
    'i.ring.16.11.hierarch-ring',
    'i.ring.16.11.father-of-mountains-ring',
    'i.ring.16.11.symbiosis-ring',
    'i.ring.16.11.inspiration-ring',
  ],
};

export const sortRecipesByOrder = (recipes, locationSlug, order = null) => {
  if (!recipes || !recipes.length) return [];
  const effectiveOrder = order || RECIPE_ORDER_CONFIG[locationSlug];
  const typeOrder = ITEM_TYPE_ORDER[locationSlug];
  const getLevel = (item) => item.minimal_level ?? item.item_details?.item?.minimal_level ?? 0;
  const getType = (item) => item.item_type || item.item_details?.item?.item_type || '';
  const getSlug = (item) => item.slug || item.item_details?.item?.slug || '';
  const getName = (item) => item.name || item.item_details?.item?.name || '';
  return [...recipes].sort((a, b) => {
    const levelA = getLevel(a), levelB = getLevel(b);
    if (levelA !== levelB) return levelA - levelB;
    if (typeOrder && typeOrder.length) {
      const idxA = typeOrder.indexOf(getType(a)), idxB = typeOrder.indexOf(getType(b));
      const orderA = idxA !== -1 ? idxA : typeOrder.length;
      const orderB = idxB !== -1 ? idxB : typeOrder.length;
      if (orderA !== orderB) return orderA - orderB;
    }
    if (effectiveOrder && effectiveOrder.length) {
      const idxA = effectiveOrder.indexOf(getSlug(a)), idxB = effectiveOrder.indexOf(getSlug(b));
      if (idxA !== -1 && idxB !== -1) return idxA - idxB;
      if (idxA !== -1) return -1;
      if (idxB !== -1) return 1;
    }
    return getName(a).localeCompare(getName(b));
  });
};

// ============================================================
// Глобальный порядок предметов для инвентаря (все локации)
// ============================================================
const GLOBAL_SLUG_ORDER = Object.values(RECIPE_ORDER_CONFIG).flat();

export const sortInventoryItems = (items) => {
  if (!items || !items.length) return [];
  return [...items].sort((a, b) => {
    const levelA = a.item?.minimal_level ?? 0;
    const levelB = b.item?.minimal_level ?? 0;
    if (levelA !== levelB) return levelA - levelB;

    const idxA = GLOBAL_SLUG_ORDER.indexOf(a.item?.slug);
    const idxB = GLOBAL_SLUG_ORDER.indexOf(b.item?.slug);
    const orderA = idxA !== -1 ? idxA : Number.MAX_SAFE_INTEGER;
    const orderB = idxB !== -1 ? idxB : Number.MAX_SAFE_INTEGER;
    if (orderA !== orderB) return orderA - orderB;

    return (a.item?.name || '').localeCompare(b.item?.name || '');
  });
};