"""
Пакет Pydantic-схем приложения ``characters``.

Схемы разбиты по доменным модулям, но все они реэкспортируются здесь,
чтобы сохранить обратную совместимость со старыми импортами вида::

    from ..schemas import TransferResult, CharacterReadSchema
    from characters_app.apps.characters.schemas import CharacterCreateDBSchema
"""

from .character import (
    CharacterCreateDBSchema,
    CharacterUpdateDBSchema,
    StatusSchema,
)
from .info import (
    CharacterInfoBaseSchema,
    CharacterInfoCreateSchema,
    CharacterInfoUpdateSchema,
    CharacterInfoUpdateDBSchema,
    CharacterInfoReadSchema,
    CharacterFullInfoSchema,
    CharacterInfoRequestSchema,
)
from .skills import (
    CharacterAbilitySkillsBaseSchema,
    CharacterAbilitySkillsCreateSchema,
    CharacterAbilitySkillsUpdateSchema,
    CharacterAbilitySkillsUpdateDBSchema,
    CharacterAbilitySkillsReadSchema,
    AppliedCharacterHistoryBaseSchema,
    AppliedCharacterHistoryCreateSchema,
    AppliedCharacterHistoryUpdateSchema,
    AppliedCharacterHistoryUpdateDBSchema,
    AppliedCharacterHistoryReadSchema,
    CharacterDistributionsBaseSchema,
    CharacterDistributionsCreateSchema,
    CharacterDistributionsUpdateSchema,
    CharacterDistributionsUpdateDBSchema,
    CharacterDistributionsReadSchema,
    AllCharacterDistributionInfo,
    ChangeSkillsRequest,
    ChangeSkillsResponse,
    EquipmentBonusesRequestSchema,
)
from .attachment import (
    CharacterAttachmentSettingsBaseSchema,
    CharacterAttachmentSettingsCreateSchema,
    CharacterAttachmentSettingsUpdateSchema,
    CharacterAttachmentSettingsUpdateDBSchema,
    CharacterAttachmentSettingsReadSchema,
)
from .trade_privileges import (
    CharacterTradePrivilegeUpdateSchema,
    CharacterTradePrivilegeReadSchema,
    CharacterTradePrivilegesInternalSchema,
)
from .internal import (
    InternalCharacterSearchItemSchema,
    InternalCharacterSearchResponseSchema,
)

from .economy import (
    CharacterDucatsOperationRequest,
    CharacterDucatsBalanceResponse,
    CharacterDucatsOperationResponse,
    CharacterCurrencyOperationRequest,
    CharacterCurrencyOperationResponse,
    CharacterCurrencyOperationReadSchema,
    CharacterCurrencyOperationListSchema,
    CharacterCurrencyOperationCurrency,
    CharacterCurrencyOperationSortBy,
    SortOrder,
    CharacterCurrencyOperationFilters,
    TransferValueCharactersSettingsBaseSchema,
    TransferValueCharactersSettingsCreateSchema,
    TransferValueCharactersSettingsUpdateSchema,
    TransferValueCharactersSettingsUpdateDBSchema,
    TransferValueCharactersSettingsReadSchema,
    CharacterTransferRequestSchema,
    TransferResult,
)
from .settings import (
    RaceSettingsBaseSchema,
    RaceSettingsCreateSchema,
    RaceSettingsUpdateSchema,
    RaceSettingsUpdateDBSchema,
    RaceSettingsReadSchema,
    GlobalCharacterSettingsBaseSchema,
    GlobalCharacterSettingsCreateSchema,
    GlobalCharacterSettingsUpdateSchema,
    GlobalCharacterSettingsUpdateDBSchema,
    GlobalCharacterSettingsReadSchema,
    GlobalCharacterExperienceSettingsBaseSchema,
    GlobalCharacterExperienceSettingsCreateSchema,
    GlobalCharacterExperienceSettingsUpdateSchema,
    GlobalCharacterExperienceSettingsUpdateDBSchema,
    GlobalCharacterExperienceSettingsReadSchema,
    UserCharacterSettingsBaseSchema,
    UserCharacterSettingsCreateSchema,
    UserCharacterSettingsUpdateSchema,
    UserCharacterSettingsUpdateDBSchema,
    UserCharacterSettingsReadSchema,
    CharacterCreationStatus,
)
from .locations import (
    LocationCreateSchema,
    LocationUpdateSchema,
    LocationUpdateDBSchema,
    LocationCharacterCountSchema,
    CityBaseSchema,
    CityCreateSchema,
    CityUpdateSchema,
    CityUpdateDBSchema,
    CityReadSchema,
)
from .activity import (
    CharacterActivityBaseSchema,
    CharacterActivityCreateSchema,
    CharacterActivityCreateDBSchema,
    CharacterActivityUpdateSchema,
    CharacterActivityUpdateDBSchema,
    CharacterActivityReadSchema,
)
from .referrals import (
    ReferralBaseSchema,
    ReferralCreateSchema,
    ReferralUpdateSchema,
    ReferralUpdateDBSchema,
    ReferralReadSchema,
    ReferralWithNameReadSchema,
    ReferralLinkBaseSchema,
    ReferralLinkCreateSchema,
    ReferralLinkUpdateSchema,
    ReferralLinkUpdateDBSchema,
    ReferralLinkReadSchema,
    ReferralLinkWithReferralsReadSchema,
    ReferralLinkWithReferralsAndUrlReadSchema,
    ReferralLinkResponseSchema,
)

__all__ = [
    # character
    'CharacterCreateDBSchema',
    'CharacterUpdateDBSchema',
    'StatusSchema',
    # info
    'CharacterInfoBaseSchema',
    'CharacterInfoCreateSchema',
    'CharacterInfoUpdateSchema',
    'CharacterInfoUpdateDBSchema',
    'CharacterInfoReadSchema',
    'CharacterFullInfoSchema',
    'CharacterInfoRequestSchema',
    # skills
    'CharacterAbilitySkillsBaseSchema',
    'CharacterAbilitySkillsCreateSchema',
    'CharacterAbilitySkillsUpdateSchema',
    'CharacterAbilitySkillsUpdateDBSchema',
    'CharacterAbilitySkillsReadSchema',
    'AppliedCharacterHistoryBaseSchema',
    'AppliedCharacterHistoryCreateSchema',
    'AppliedCharacterHistoryUpdateSchema',
    'AppliedCharacterHistoryUpdateDBSchema',
    'AppliedCharacterHistoryReadSchema',
    'CharacterDistributionsBaseSchema',
    'CharacterDistributionsCreateSchema',
    'CharacterDistributionsUpdateSchema',
    'CharacterDistributionsUpdateDBSchema',
    'CharacterDistributionsReadSchema',
    'AllCharacterDistributionInfo',
    'ChangeSkillsRequest',
    'ChangeSkillsResponse',
    'EquipmentBonusesRequestSchema',
    # attachment
    'CharacterAttachmentSettingsBaseSchema',
    'CharacterAttachmentSettingsCreateSchema',
    'CharacterAttachmentSettingsUpdateSchema',
    'CharacterAttachmentSettingsUpdateDBSchema',
    'CharacterAttachmentSettingsReadSchema',
    # trade_privileges
    'CharacterTradePrivilegeUpdateSchema',
    'CharacterTradePrivilegeReadSchema',
    'CharacterTradePrivilegesInternalSchema',
    # internal
    'InternalCharacterSearchItemSchema',
    'InternalCharacterSearchResponseSchema',
    # economy
    'CharacterDucatsOperationRequest',
    'CharacterDucatsBalanceResponse',
    'CharacterDucatsOperationResponse',
    'CharacterCurrencyOperationRequest',
    'CharacterCurrencyOperationResponse',
    'CharacterCurrencyOperationReadSchema',
    'CharacterCurrencyOperationListSchema',
    'CharacterCurrencyOperationCurrency',
    'CharacterCurrencyOperationSortBy',
    'SortOrder',
    'CharacterCurrencyOperationFilters',
    'TransferValueCharactersSettingsBaseSchema',
    'TransferValueCharactersSettingsCreateSchema',
    'TransferValueCharactersSettingsUpdateSchema',
    'TransferValueCharactersSettingsUpdateDBSchema',
    'TransferValueCharactersSettingsReadSchema',
    'CharacterTransferRequestSchema',
    'TransferResult',
    # settings
    'RaceSettingsBaseSchema',
    'RaceSettingsCreateSchema',
    'RaceSettingsUpdateSchema',
    'RaceSettingsUpdateDBSchema',
    'RaceSettingsReadSchema',
    'GlobalCharacterSettingsBaseSchema',
    'GlobalCharacterSettingsCreateSchema',
    'GlobalCharacterSettingsUpdateSchema',
    'GlobalCharacterSettingsUpdateDBSchema',
    'GlobalCharacterSettingsReadSchema',
    'GlobalCharacterExperienceSettingsBaseSchema',
    'GlobalCharacterExperienceSettingsCreateSchema',
    'GlobalCharacterExperienceSettingsUpdateSchema',
    'GlobalCharacterExperienceSettingsUpdateDBSchema',
    'GlobalCharacterExperienceSettingsReadSchema',
    'UserCharacterSettingsBaseSchema',
    'UserCharacterSettingsCreateSchema',
    'UserCharacterSettingsUpdateSchema',
    'UserCharacterSettingsUpdateDBSchema',
    'UserCharacterSettingsReadSchema',
    'CharacterCreationStatus',
    # locations
    'LocationCreateSchema',
    'LocationUpdateSchema',
    'LocationUpdateDBSchema',
    'LocationCharacterCountSchema',
    'CityBaseSchema',
    'CityCreateSchema',
    'CityUpdateSchema',
    'CityUpdateDBSchema',
    'CityReadSchema',
    # activity
    'CharacterActivityBaseSchema',
    'CharacterActivityCreateSchema',
    'CharacterActivityCreateDBSchema',
    'CharacterActivityUpdateSchema',
    'CharacterActivityUpdateDBSchema',
    'CharacterActivityReadSchema',
    # referrals
    'ReferralBaseSchema',
    'ReferralCreateSchema',
    'ReferralUpdateSchema',
    'ReferralUpdateDBSchema',
    'ReferralReadSchema',
    'ReferralWithNameReadSchema',
    'ReferralLinkBaseSchema',
    'ReferralLinkCreateSchema',
    'ReferralLinkUpdateSchema',
    'ReferralLinkUpdateDBSchema',
    'ReferralLinkReadSchema',
    'ReferralLinkWithReferralsReadSchema',
    'ReferralLinkWithReferralsAndUrlReadSchema',
    'ReferralLinkResponseSchema',
]


